import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Pool OS',
      'dashboard': 'Dashboard',
      'session': 'Session',
      'equipment': 'Equipment',
      'player': 'Player',
      'settings': 'Settings',
      'start_session': 'Start Session',
      'finish_session': 'Finish Session',
      'add_shot': 'Add Shot',
      'add_rack': 'Add Rack',
      'add_event': 'Add Event',
      'record_shot_first': 'Record a shot first before adding an event',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'no_data': 'No data available',
      'session_type': 'Session Type',
      'practice': 'Practice',
      'match': 'Match',
      'hybrid': 'Hybrid',
      'experiment': 'Experiment',
      'session_notes': 'Session Notes',
      'player_name': 'Player Name',
      'dominant_hand': 'Dominant Hand',
      'language': 'Language',
      'measurement_system': 'Measurement System',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'left': 'Left',
      'right': 'Right',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'cm': 'cm',
      'inch': 'inch',
      'rack_win': 'Win',
      'rack_loss': 'Loss',
      'shot_made': 'Made',
      'shot_missed': 'Missed',
      'cue': 'Cue',
      'shaft': 'Shaft',
      'shaft_material': 'Shaft Material',
      'shaft_diameter': 'Shaft Diameter',
      'tip': 'Tip',
      'tip_brand': 'Tip Brand',
      'tip_hardness': 'Tip Hardness',
      'tip_size': 'Tip Size',
      'cue_type': 'Cue Type',
      'weight': 'Weight',
      'balance': 'Balance',
      'joint': 'Joint',
      'active_cue': 'Active Cue',
      'active_break_cue': 'Active Break Cue',
      'active_jump_cue': 'Active Jump Cue',
      'history': 'History',
      'position_quality': 'Position Quality',
      'perfect': 'Perfect',
      'good': 'Good',
      'playable': 'Playable',
      'recovery': 'Recovery',
      'bad': 'Bad',
      'notes': 'Notes',
      'statistics': 'Statistics',
      'career': 'Career',
      'session_history': 'Session History',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'confirm': 'Confirm',
      'warning': 'Warning',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'empty_state': 'No records yet',
      'tap_to_add': 'Tap + to add',
      'today_dashboard': 'Today Dashboard',
      'skill_dashboard': 'Skill Dashboard',
      'trend_dashboard': 'Trend Dashboard',
      'drill_library': 'Drill Library',
      'start_drill': 'Start Drill',
      'record_drill': 'Record Drill',
      'personal_best': 'Personal Best',
      'export_json': 'Export JSON',
      'export_csv': 'Export CSV',
      'backup_database': 'Backup Database',
      'coach_ai': 'Coach AI',
      'training_program': 'Training Program',
      'achievements': 'Achievements',
      'career_dashboard': 'Career Dashboard',
      'training': 'Training',
      'matches': 'Matches',
      'new_match': 'New Match',
      'no_matches_yet': 'No matches yet',
      'play_matches_to_see_stats': 'Play matches to see your win rate statistics',
      'match_history': 'Match History',
      'no_racks_yet': 'No racks yet',
      'play_racks_to_see_stats': 'Play racks to see detailed statistics',
      'rack_history': 'Rack History',
      'no_shots_yet': 'No shots yet',
      'take_shots_to_see_stats': 'Take shots to see shot statistics',
      'shots_by_type': 'Shots by Type',
      'shots_by_difficulty': 'Shots by Difficulty',
      'total_shots': 'Total Shots',
      'made_shots': 'Made',
      'missed_shots': 'Missed',
      'no_errors_recorded': 'No errors recorded',
      'great_performance': 'Great performance! Keep it up!',
      'error_by_type': 'Errors by Type',
      'error_timeline': 'Error Timeline',
      'error_count_description': 'Recorded during practice sessions',
      'no_breaks_yet': 'No breaks yet',
      'play_breaks_to_see_stats': 'Play breaks to see break statistics',
      'break_history': 'Break History',
      'total_breaks': 'Total Breaks',
      'successful_breaks': 'Successful',
      'dry_breaks': 'Dry Breaks',
      'break_scratches': 'Scratches',
      'success_rate': 'Success Rate',
      'avg_balls_pocketed': 'Avg Balls',
      'win_rate_detail': 'Win Rate Detail',
      'rack_detail': 'Rack Detail',
      'shot_statistics': 'Shot Statistics',
      'error_statistics': 'Error Statistics',
      'break_statistics': 'Break Statistics',
      'detailed_statistics': 'Detailed Statistics',
      'total_matches': 'Total Matches',
      'wins': 'Wins',
      'losses': 'Losses',
      'racks_won': 'Won',
      'racks_lost': 'Lost',
      'confidence': 'Confidence',
      'balls_run': 'Balls',
      'total_errors': 'Total Errors',
      'scratch': 'Scratch',
      'balls': 'balls',
      'run': 'Run',
      'error_loading_stats': 'Error loading statistics',
      'total_racks': 'Total Racks',
      'active': 'Active',
      'warm_up': 'Warm Up',
      'ghost_challenge': 'Ghost Challenge',
      'challenge_match': 'Challenge Match',
      'league_match': 'League Match',
      'tournament_match': 'Tournament Match',
      'practice_match': 'Practice Match',
      'drill': 'Drill',
      'sessions': 'Sessions',
      'rack_count': 'Racks',
      'shot_count': 'Shots',
      'event_count': 'Events',
      'session_duration': 'Duration',
      'notes_placeholder': 'Add notes here...',
      'performance': 'Performance',
      'best_strength': 'Best Strength',
      'balls_potted': 'Balls Potted',
      'largest_run': 'Largest Run',
      'break_success': 'Success',
      'position_error': 'Position',
      'safety_error': 'Safety',
      'kick_error': 'Kick',
      'jump_error': 'Jump',
      'easy_miss': 'Easy Miss',
      'hard_miss': 'Hard Miss',
      'select_type': 'Select type',
      'select_hand': 'Select dominant hand',
      'select_language': 'Select language',
      'select_measurement': 'Select measurement system',
      'select_theme': 'Select theme',
      'session_summary': 'Session Summary',
      'session_stats': 'Statistics',
      'delete_session': 'Delete Session',
      'duplicate_session': 'Duplicate Session',
      'are_you_sure': 'Are you sure?',
      'yes': 'Yes',
      'no': 'No',
      'conversations': 'Conversations',
      'new_conversation': 'New Conversation',
      'conversation_title_hint': 'Enter conversation title',
      'chat': 'Chat',
      'type_message': 'Type a message...',
      'send': 'Send',
      'no_messages': 'No messages yet',
      'delete_conversation': 'Delete Conversation',
      'create': 'Create',
      'skill_stroke': 'Stroke',
      'skill_stroke_desc': 'Your stroke smoothness and cue delivery',
      'skill_position': 'Position',
      'skill_position_desc': 'Position play and ball control',
      'skill_decision': 'Decision',
      'skill_decision_desc': 'Shot selection and safety play',
      'skill_pattern': 'Pattern',
      'skill_pattern_desc': 'Pattern recognition and run outs',
      'skill_break': 'Break',
      'skill_break_desc': 'Break effectiveness and ball scatter',
      'skill_safety': 'Safety',
      'skill_safety_desc': 'Safety play and leave planning',
      'skill_mental': 'Mental',
      'skill_mental_desc': 'Pressure handling and focus',
      'skill_consistency': 'Consistency',
      'skill_consistency_desc': 'Reliable performance across sessions',
      'skill_equipment': 'Equipment',
      'skill_equipment_desc': 'Adaptation to different cues and tables',
      'skill_recovery': 'Recovery',
      'skill_recovery_desc': 'Recovery after mistakes',
      'skill_radar': 'Skill Radar',
      'skill_cards': 'Skill Cards',
      'skill_timeline': 'Skill Timeline',
      'skill_heatmap': 'Skill Heatmap',
      'skill_overview': 'Skill Overview',
      'skill_confidence': 'Confidence',
      'skill_trend': 'Trend',
      'skill_improving': 'Improving',
      'skill_stable': 'Stable',
      'skill_declining': 'Declining',
      'skill_elite': 'Elite',
      'skill_excellent': 'Excellent',
      'skill_advanced': 'Advanced',
      'skill_intermediate': 'Intermediate',
      'skill_developing': 'Developing',
      'skill_needs_improvement': 'Needs Improvement',
      'low_confidence_warning': 'Low confidence - more data needed',
      'career_progress': 'Career Progress',
      'training_focus': 'Training Focus',
      'no_skills_yet': 'No skills calculated yet',
      'calculate_skills': 'Calculate Skills',
      'last_updated': 'Last updated',
      'daily_readiness': 'Daily Readiness',
      'today_readiness': "Today's Readiness",
      'physical_condition': 'Physical Condition',
      'sleep_hours': 'Sleep Hours',
      'energy_level': 'Energy Level',
      'focus_level': 'Focus Level',
      'confidence_level': 'Confidence Level',
      'stress_level': 'Stress Level',
      'mood': 'Mood',
      'physical_check': 'Physical Check',
      'shoulder_condition': 'Shoulder Condition',
      'arm_condition': 'Arm Condition',
      'session_prep': 'Session Prep',
      'playing_location': 'Playing Location',
      'table_speed': 'Table Speed',
      'today_goal': "Today's Goal",
      'how_feeling': 'How are you feeling?',
      'goal_hint': 'What do you want to achieve today?',
      'notes_hint': 'Any additional notes...',
      'location_club': 'Club',
      'location_home': 'Home',
      'location_academy': 'Academy',
      'location_tournament': 'Tournament',
      'table_slow': 'Slow',
      'table_medium': 'Medium',
      'table_fast': 'Fast',
      'mood_great': 'Great',
      'mood_good': 'Good',
      'mood_okay': 'Okay',
      'mood_tired': 'Tired',
      'mood_bad': 'Bad',
      'condition_excellent': 'Excellent',
      'condition_good': 'Good',
      'condition_okay': 'Okay',
      'condition_tight': 'Tight',
      'condition_painful': 'Painful',
      'readiness_excellent': 'Excellent',
      'readiness_good': 'Good',
      'readiness_moderate': 'Moderate',
      'readiness_low': 'Low',
      'readiness_poor': 'Poor',
      'quick_actions': 'Quick Actions',
      'start_practice': 'Start Practice',
      'start_match': 'Start Match',
      'continue_session': 'Continue',
      'current_equipment': 'Current Equipment',
      'break_cue': 'Break Cue',
      'cue_type_playing': 'Playing Cue',
      'cue_type_break': 'Break Cue',
      'cue_type_jump': 'Jump Cue',
      'cue_type_break_jump': 'Break + Jump',
      'cue_type_support': 'Support',
      'add_equipment': 'Add your first cue',
      'coach_insight': 'Coach Insight',
      'weekly_trend': 'This Week',
      'monthly_trend': 'This Month',
      'recent_sessions': 'Recent Sessions',
      'see_all': 'See All',
      'no_sessions_yet': 'No sessions yet',
      'log_readiness': 'Log your readiness',
      'tap_to_log': 'Tap to log today\'s condition',
      'performance_score': 'Performance Score',
      'break_and_run': 'Break & Run',
      'session_finished': 'Session finished!',
      'view_summary': 'View Summary',
      'select_match_type': 'Select Match Type',
      'select_session_type': 'Select Session Type',
      'match_details': 'Match Details',
      'finish_match': 'Finish Match',
      'edit_match': 'Edit Match',
      'delete_match': 'Delete Match',
      'no_racks': 'No racks yet',
      'opponent': 'Opponent',
      'race_to': 'Race to',
      'race_to_custom': 'Custom race to…',
      'race_to_5': 'Race to 5',
      'race_to_7': 'Race to 7',
      'select_winner': 'Select Winner',
      'match_winner': 'Match Winner',
      'you': 'You',
      'winner': 'Winner',
      'select_as_active': 'Select as Active',
      'add_cue': 'Add Cue',
      'edit_cue': 'Edit Cue',
      'cue_name': 'Cue Name',
      'details': 'Details',
      'cue_added': 'Cue added successfully',
      'cue_updated': 'Cue updated successfully',
      'cue_deleted': 'Cue deleted',
      'delete_cue_confirm': 'Delete cue',
      'coach': 'Coach',
      'overview': 'Overview',
      'insights': 'Insights',
      'ask': 'Ask',
      'ask_coach_hint': 'Ask your coach...',
      'no_insights': 'No insights yet',
      'play_sessions_for_insights':
          'Play more sessions to get personalized insights',
      'training_advice': 'Training Advice',
      'strengths': 'Strengths',
      'weaknesses': 'Areas to Improve',
      'coach_summary': 'Coach Summary',
      'recommended_drill': 'Recommended Drill',
      'definition': 'Definition',
      'calculation': 'Calculation',
      'target': 'Target',
      'advice': 'Advice',
      'trend': 'Trend',
      'current_value': 'Current Value',
      'total_wins': 'Total Wins',
      'total_losses': 'Total Losses',
      'win_rate': 'Win Rate',
      'shot_accuracy': 'Shot Accuracy',
      'career_accuracy': 'Career Accuracy',
      'recent_performance': 'Recent Performance',
      'improvement_tips': 'Improvement Tips',
      'weekly_performance': 'Weekly Performance',
      'accuracy_trend': 'Accuracy Trend',
      'close': 'Close',
      'total_events': 'Total Events',
      'no_players_yet': 'No players yet',
      'create_first_player': 'Create your first player to get started',
      'add_player': 'Add Player',
      'delete_player': 'Delete Player',
      'are_you_sure_delete': 'Are you sure you want to delete',
      'skill_level': 'Skill Level',
      'default_equipment': 'Default Equipment',
      'cue_name_hint': 'e.g., Predator REVO',
      'select_avatar_color': 'Select Avatar Color',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'expert': 'Expert',
      'professional': 'Professional',
      'name_required': 'Name is required',
      'ghost_skill_level': 'Ghost Skill Level',
      'ghost_challenge_won': 'You Won!',
      'ghost_challenge_lost': 'Ghost Wins!',
      'ghost_challenge_tie': "It's a Tie!",
      'reset_challenge': 'Reset Challenge',
      'new_challenge': 'New Challenge',
      'who_won_rack': 'Who won this rack?',
      'drill_progress': 'Drill Progress',
      'drill_complete': 'Drill Complete!',
      'drill_instructions': 'Instructions',
      'try_again': 'Try Again',
      'filter_drills': 'Filter Drills',
      'category': 'Category',
      'difficulty': 'Difficulty',
      'duration': 'Duration',
      'focus_areas': 'Focus Areas',
      'clear_filters': 'Clear Filters',
      'no_drills_found': 'No drills found',
      'adjust_filters': 'Try adjusting your filters',
      'enroll_program': 'Enroll in Program',
      'withdraw_program': 'Withdraw from Program',
      'program_progress': 'Program Progress',
      'current_week': 'Week {current}/{total}',
      'sessions_completed': '{completed}/{total} sessions',
      'upcoming_sessions': 'Upcoming Sessions',
      'program_overview': 'Program Overview',
      'phases': 'Phases',
      'total_sessions': 'Total Sessions',
      'session_length': 'Session Length',
      'week_progress': 'Week {number} Progress',
      'confirm_withdraw': 'Withdraw from Program?',
      'withdraw_warning':
          'Your progress will be saved but you will need to restart.',
      'shot_type': 'Shot Type',
      'shot_difficulty': 'Difficulty',
      'shot_result': 'Result',
      'quick_add': 'Quick Add',
      'shot_history': 'Shot History',
      'clear_all_shots': 'Clear All',
      'undo_last_shot': 'Undo Last Shot',
      'made': 'Made',
      'missed': 'Missed',
      'foul': 'Foul',
      'break': 'Break',
      'accuracy': 'Accuracy',
      'event_category': 'Category',
      'event_type': 'Type',
      'event_severity': 'Severity',
      'great_shot': 'Great Shot',
      'mistake': 'Mistake',
      'safety_won': 'Safety Won',
      'safety_lost': 'Safety Lost',
      'dry_break': 'Dry Break',
      'mental_event': 'Mental',
      'event_history': 'Event History',
      'minor': 'Minor',
      'moderate': 'Moderate',
      'significant': 'Significant',
      'critical': 'Critical',
      'goals': 'Goals',
      'add_goal': 'Add Goal',
      'today_goals': "Today's Goals",
      'all_goals': 'All Goals',
      'goal_progress': 'Goal Progress',
      'goals_completed': 'Goals Completed',
      'set_goals': 'Set Goals',
      'priority': 'Priority',
      'low': 'Low',
      'high': 'High',
      'urgent': 'Urgent',
      'completed': 'Completed',
      'abandoned': 'Abandoned',
      'overdue': 'Overdue',
      'days_remaining': '{days} days remaining',
      'abandon_goal': 'Abandon Goal',
      'delete_goal': 'Delete Goal',
      'current_vs_previous': 'Current vs Previous',
      'skill_comparison': 'Skill Comparison',
      'improvement': 'Improvement',
      'undo_rack': 'Undo Last Rack',
      'undo_rack_confirm': 'Undo Last Rack?',
      'undo_rack_message':
          'This will remove rack #{number} and update the match stats.',
      'rack_undone': 'Rack #{number} undone',
      // Dashboard
      'quick_stats': 'Quick Stats',
      'today_focus': "Today's Focus",
      'current_streak': 'Day Streak',
      'weekly_hours': 'This Week',
      'no_skills': 'No skill data yet',
      'last_matches': 'Last 10 Matches',
      'no_matches': 'No matches yet',
      'won': 'Won',
      'lost': 'Lost',
      'in_progress': 'In Progress',
      'unknown_cue': 'Unknown Cue',
      'unknown_date': 'Unknown date',
      'unknown_error': 'Unknown error',
      'retry': 'Retry',
      'error_loading_data': 'Error loading data',
      // Session
      'view_details': 'View Details',
      // Equipment
      'my_cue': 'My Cue',
      'please_enter_cue_name': 'Please enter a cue name',
      'set_as_active_cue': '{name} set as active cue',
      'set_as_break_cue': '{name} set as break cue',
      'set_as_jump_cue': '{name} set as jump cue',
      // Match
      'race_to_progress': '{raceTo} Progress',
      'match_info': 'Match Info',
      'started': 'Started',
      'ended': 'Ended',
      'rack_timeline': 'Rack Timeline',
      'racks': 'racks',
      'record_rack_result': 'Record Rack Result',
      'tap_to_record_rack': 'Tap to record the outcome of the next rack',
      'no_racks_to_undo': 'No racks to undo',
      'undo_rack_action': 'Undo',
      'finished': 'Finished',
      // Statistics
      'detailed_stats': 'Detailed Stats',
      'event_analysis': 'Event Analysis',
      'by_category': 'By Category:',
      'play_more_sessions_skills': 'Play more sessions to see your skill analysis',
      'data_points': 'data points',
      'performance_metrics': 'Your performance metrics over the tracked period',
      'aggregated_sessions': 'Aggregated from all sessions and racks',
      'improve_weekly': 'Improve by 5% each week',
      'adjust_practice': "Review what worked and what didn't. Adjust practice focus accordingly.",
      'accuracy_over_time': 'How your shot-making accuracy has changed over time',
      'rolling_average': 'Rolling average of shot success rate',
      'reach_70_accuracy': 'Reach and maintain 70%+ accuracy',
      'focus_alignment': 'Focus on alignment and cue delivery. Record your practice sessions to review.',
      'focus_position_play': 'Focus on position play to create more scoring opportunities',
      'practice_fundamentals': 'Practice fundamental shots and alignment techniques',
      'play_more_sessions': 'Play more sessions to build consistent data',
      'keep_up_great_work': 'Keep up the great work! Your performance is excellent.',
      'stat_not_enough_data': 'Not enough data yet.',
      'stat_play_more_unlock': 'Play more matches to unlock analysis.',
      'stat_match_won': 'Matches Won',
      'stat_avg_balls_potted': 'Average Balls Potted',
      'stat_avg_largest_run': 'Average Largest Run',
      'stat_avg_break_success': 'Average Break Success',
      'stat_avg_confidence': 'Average Confidence',
      'stat_common_mistakes': 'Common Mistakes',
      'stat_common_strengths': 'Common Strengths',
      'stat_coach_insight': 'Coach Insight',
      'stat_category': 'Category',
      'stat_metric': 'Metric',
      'stat_detail': 'Detail',
      'stat_recommendation': 'Recommendation',
      'stat_no_data': 'No Data',
      'stat_insight_reason': 'Reason',
      'stat_insight_recommendation': 'Recommendation',
      'stat_insight_benefit': 'Expected Benefit',
      'stat_trend_current': 'Current',
      'stat_trend_previous': 'Previous',
      'stat_trend_difference': 'Difference',
      'stat_reason': 'Reason',
      'stat_expected_improvement': 'Expected Improvement',
      'stat_common_miss_type': 'Common Miss Type',
      'stat_most_frequent_error': 'Most Frequent Error',
      'stat_accuracy_trend': 'Accuracy Trend',
      'stat_main_reason': 'Main Reason',
      'stat_improvement_suggestion': 'Improvement Suggestion',
      'stat_drill_down_title': 'Drill-down Analysis',
      'stat_summary': 'Summary',
      'stat_drill_down_empty': 'Not enough data yet. Play more matches to unlock analysis.',
      'stat_recommendation_source': 'Because {reason}, recommend {drill}.',
      // Coach
      'analysis': 'Analysis',
      'coach_score': 'Coach Score',
      'skill_score': 'Skill Score',
      'trend_score': 'Trend Score',
      // Daily Readiness
      'ready_score': 'Ready',
      'recovery_score': 'Recovery',
      'wrist_condition': 'Wrist',
      'back_condition': 'Back',
      // Session Summary
      'suggested': 'Suggested',
      // Rack
      'rack_summary': 'Rack Summary',
      'biggest_mistake': 'Biggest Mistake',
      'biggest_strength': 'Biggest Strength',
      'rack_confidence': 'Confidence',
      'confidence_very_low': 'Very Low',
      'confidence_low': 'Low',
      'confidence_medium': 'Medium',
      'confidence_high': 'High',
      'confidence_very_high': 'Very High',
      // Settings
      'system_default': 'System Default',
      'measurement_cm': 'Centimeters (cm)',
      'measurement_inch': 'Inches (in)',
      // Match Selection
      'select_match': 'Select Match',
      'continue_match': 'Continue Match',
      'no_sessions_to_continue': 'No sessions to continue',
      // Coach Presentation
      'coach_no_recommendations': 'No recommendations yet. Complete more sessions for analysis.',
      'coach_todays_focus': "Today's Focus",
      'coach_primary_focus': 'Primary Focus',
      'coach_secondary_focus': 'Secondary Focus',
      'coach_observation': 'Problem',
      'coach_evidence': 'Reason',
      'coach_expected_improvement': 'Expected Improvement',
      'coach_recommended_drill': 'Recommended Drills',
      'coach_problem': 'Problem',
      'coach_reason': 'Reason',
      'coach_benefit': 'Expected Benefit',
      'coach_no_training_plan': 'No training plan yet',
      'coach_complete_sessions_for_plan': 'Complete more sessions to receive personalized training plans',
      'coach_todays_plan': "Today's Plan",
      'coach_start_training': 'Start Training',
      'coach_drill_info': 'Drill Info',
      'coach_difficulty': 'Difficulty',
      'coach_duration': 'Duration',
      'coach_short_description': 'Short Description',
      'coach_start_drill': 'Start Drill',
      'coach_unavailable': 'Unavailable',
      'coach_history_today': 'Today',
      'coach_history_yesterday': 'Yesterday',
      'coach_history_last_7_days': 'Last 7 Days',
      'coach_history_last_30_days': 'Last 30 Days',
      'coach_history_completed': 'Completed',
      'coach_history_result': 'Result',
      'coach_performance': 'Performance',
      'coach_consistency': 'Consistency',
      'coach_confidence': 'Confidence',
      'coach_training_distribution': 'Training Distribution',
      'coach_improvement': 'Improvement',
      'coach_regression': 'Regression',
      'coach_equipment_analysis': 'Equipment Analysis',
      'coach_match_analysis': 'Match Analysis',
      'coach_recommendation_history': 'Recommendation History',
      'coach_not_enough_data': 'Not enough data yet. Play more matches to unlock AI analysis.',
      'warmup': 'Warmup',
      'cooldown': 'Cooldown',
      'minutes_short': 'min',
      'drills_short': 'drills',
      'target_score': 'target score',
      'intensity_heavy': 'Heavy',
      'intensity_normal': 'Normal',
      'intensity_light': 'Light',
      'intensity_recovery': 'Recovery',
      'category_health': 'Health',
      'category_readiness': 'Readiness',
      'category_mental': 'Mental',
      'category_skill_weakness': 'Weakness',
      'category_training_plan': 'Plan',
      'category_equipment': 'Equipment',
      'category_recovery': 'Recovery',
      'category_general': 'General',
    },
    'vi': {
      'app_name': 'Pool OS',
      'dashboard': 'Trang chủ',
      'session': 'Buổi chơi',
      'equipment': 'Cơ',
      'player': 'Người chơi',
      'settings': 'Cài đặt',
      'start_session': 'Bắt đầu buổi',
      'finish_session': 'Kết thúc buổi',
      'add_shot': 'Thêm cú đánh',
      'add_rack': 'Thêm ván',
      'add_event': 'Thêm sự kiện',
      'record_shot_first': 'Ghi một cú đánh trước khi thêm sự kiện',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'edit': 'Sửa',
      'today': 'Hôm nay',
      'yesterday': 'Hôm qua',
      'no_data': 'Chưa có dữ liệu',
      'session_type': 'Loại buổi',
      'practice': 'Luyện tập',
      'match': 'Đấu',
      'hybrid': 'Kết hợp',
      'experiment': 'Thử nghiệm',
      'session_notes': 'Ghi chú buổi',
      'player_name': 'Tên người chơi',
      'dominant_hand': 'Tay thuận',
      'language': 'Ngôn ngữ',
      'measurement_system': 'Đơn vị đo',
      'theme': 'Giao diện',
      'dark_mode': 'Tối',
      'light_mode': 'Sáng',
      'left': 'Trái',
      'right': 'Phải',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'cm': 'cm',
      'inch': 'inch',
      'rack_win': 'Thắng',
      'rack_loss': 'Thua',
      'shot_made': 'Đánh trúng',
      'shot_missed': 'Trượt',
      'cue': 'Cơ',
      'shaft': 'Can',
      'shaft_material': 'Chất liệu cần',
      'shaft_diameter': 'Đường kính cần',
      'tip': 'Đầu cơ',
      'tip_brand': 'Thương hiệu đầu cơ',
      'tip_hardness': 'Độ cứng đầu cơ',
      'tip_size': 'Kích thước đầu cơ',
      'cue_type': 'Loại cơ',
      'weight': 'Trọng lượng',
      'balance': 'Cân bằng',
      'joint': 'Khớp',
      'active_cue': 'Cơ đang dùng',
      'active_break_cue': 'Cơ phá đang dùng',
      'history': 'Lịch sử',
      'position_quality': 'Chất lượng điều bi',
      'perfect': 'Hoàn hảo',
      'good': 'Tốt',
      'playable': 'Chơi được',
      'recovery': 'Cứu',
      'bad': 'Xấu',
      'notes': 'Ghi chú',
      'statistics': 'Thống kê',
      'career': 'Sự nghiệp',
      'session_history': 'Lịch sử buổi',
      'back': 'Quay lại',
      'next': 'Tiếp',
      'done': 'Xong',
      'confirm': 'Xác nhận',
      'warning': 'Cảnh báo',
      'error': 'Lỗi',
      'success': 'Thành công',
      'loading': 'Đang tải...',
      'empty_state': 'Chưa có dữ liệu',
      'tap_to_add': 'Bấm + để thêm',
      'today_dashboard': 'Hôm nay',
      'skill_dashboard': 'Kỹ năng',
      'trend_dashboard': 'Xu hướng',
      'drill_library': 'Thư viện bài tập',
      'start_drill': 'Bắt đầu tập',
      'record_drill': 'Ghi lại',
      'personal_best': 'Kỷ lục cá nhân',
      'export_json': 'Xuất JSON',
      'export_csv': 'Xuất CSV',
      'backup_database': 'Sao lưu',
      'coach_ai': 'Huấn luyện viên AI',
      'training_program': 'Chương trình tập',
      'achievements': 'Thành tích',
      'career_dashboard': 'Sự nghiệp',
      'training': 'Tập luyện',
      'matches': 'Trận đấu',
      'new_match': 'Trận mới',
      'no_matches_yet': 'Chưa có trận nào',
      'play_matches_to_see_stats': 'Chơi các trận để xem thống kê tỷ lệ thắng',
      'match_history': 'Lịch sử trận đấu',
      'no_racks_yet': 'Chưa có ván nào',
      'play_racks_to_see_stats': 'Chơi các ván để xem thống kê chi tiết',
      'rack_history': 'Lịch sử ván',
      'no_shots_yet': 'Chưa có cú đánh nào',
      'take_shots_to_see_stats': 'Đánh các cú để xem thống kê',
      'shots_by_type': 'Cú đánh theo loại',
      'shots_by_difficulty': 'Cú đánh theo độ khó',
      'total_shots': 'Tổng cú đánh',
      'made_shots': 'Đánh trúng',
      'missed_shots': 'Đánh trượt',
      'no_errors_recorded': 'Không có lỗi nào được ghi',
      'great_performance': 'Xuất sắc! Tiếp tục phát huy!',
      'error_by_type': 'Lỗi theo loại',
      'error_timeline': 'Dòng thời gian lỗi',
      'error_count_description': 'Được ghi trong buổi tập',
      'no_breaks_yet': 'Chưa có break nào',
      'play_breaks_to_see_stats': 'Chơi break để xem thống kê',
      'break_history': 'Lịch sử break',
      'total_breaks': 'Tổng Break',
      'successful_breaks': 'Thành công',
      'dry_breaks': 'Break khô',
      'break_scratches': 'Scratch',
      'success_rate': 'Tỷ lệ thành công',
      'avg_balls_pocketed': 'TB Bóng',
      'win_rate_detail': 'Chi tiết tỷ lệ thắng',
      'rack_detail': 'Chi tiết ván',
      'shot_statistics': 'Thống kê cú đánh',
      'error_statistics': 'Thống kê lỗi',
      'break_statistics': 'Thống kê Break',
      'detailed_statistics': 'Thống kê chi tiết',
      'total_matches': 'Tổng trận',
      'wins': 'Thắng',
      'losses': 'Thua',
      'racks_won': 'Thắng',
      'racks_lost': 'Thua',
      'confidence': 'Tự tin',
      'balls_run': 'Bóng',
      'total_errors': 'Tổng lỗi',
      'scratch': 'Scratch',
      'balls': 'bóng',
      'run': 'Chạy',
      'error_loading_stats': 'Lỗi tải thống kê',
      'total_racks': 'Tổng ván',
      'active': 'Đang chơi',
      'warm_up': 'Khởi động',
      'ghost_challenge': 'Đấu ma',
      'challenge_match': 'Đấu thách đấu',
      'league_match': 'Đấu giải',
      'tournament_match': 'Đấu giải đấu',
      'practice_match': 'Đấu tập',
      'drill': 'Bài tập',
      'sessions': 'Buổi chơi',
      'rack_count': 'Ván',
      'shot_count': 'Cú đánh',
      'event_count': 'Sự kiện',
      'session_duration': 'Thời gian',
      'notes_placeholder': 'Thêm ghi chú...',
      'performance': 'Hiệu suất',
      'best_strength': 'Điểm mạnh',
      'balls_potted': 'Bi vào lỗ',
      'largest_run': 'Chuỗi dài nhất',
      'break_success': 'Thành công',
      'position_error': 'Vị trí',
      'safety_error': 'An toàn',
      'kick_error': 'Đá bi',
      'jump_error': 'Nhảy',
      'easy_miss': 'Sai dễ',
      'hard_miss': 'Sai khó',
      'select_type': 'Chọn loại',
      'select_hand': 'Chọn tay thuận',
      'select_language': 'Chọn ngôn ngữ',
      'select_measurement': 'Chọn đơn vị đo',
      'select_theme': 'Chọn giao diện',
      'session_summary': 'Tóm tắt buổi',
      'session_stats': 'Thống kê',
      'delete_session': 'Xóa buổi',
      'duplicate_session': 'Nhân bản buổi',
      'are_you_sure': 'Bạn có chắc?',
      'yes': 'Có',
      'no': 'Không',
      'conversations': 'Trò truyện',
      'new_conversation': 'Cuộc trò truyện mới',
      'conversation_title_hint': 'Nhập tiêu đề cuộc trò truyện',
      'chat': 'Trò truyện',
      'type_message': 'Nhập tin nhắn...',
      'send': 'Gửi',
      'no_messages': 'Chưa có tin nhắn',
      'delete_conversation': 'Xóa cuộc trò truyện',
      'create': 'Tạo',
      'skill_stroke': 'Đánh cơ',
      'skill_stroke_desc': 'Độ mượt mà của cú đánh',
      'skill_position': 'Điều bi',
      'skill_position_desc': 'Kiểm soát vị trí và bi',
      'skill_decision': 'Quyết định',
      'skill_decision_desc': 'Chọn cú đánh và chơi an toàn',
      'skill_pattern': 'Quỹ đạo',
      'skill_pattern_desc': 'Nhận diện quỹ đạo và chạy bàn',
      'skill_break': 'Phá bàn',
      'skill_break_desc': 'Hiệu quả phá bàn',
      'skill_safety': 'An toàn',
      'skill_safety_desc': 'Chơi an toàn và lên kế hoạch',
      'skill_mental': 'Tâm lý',
      'skill_mental_desc': 'Xử lý áp lực và tập trung',
      'skill_consistency': 'Ổn định',
      'skill_consistency_desc': 'Thành tích ổn định qua các buổi',
      'skill_equipment': 'Công cụ',
      'skill_equipment_desc': 'Thích nghi với cơ và bàn khác nhau',
      'skill_recovery': 'Phục hồi',
      'skill_recovery_desc': 'Khắc phục sau sai lầm',
      'skill_radar': 'Radar Kỹ năng',
      'skill_cards': 'Thẻ Kỹ năng',
      'skill_timeline': 'Dòng thời gian',
      'skill_heatmap': 'Bản đồ nhiệt',
      'skill_overview': 'Tổng quan',
      'skill_confidence': 'Độ tin cậy',
      'skill_trend': 'Xu hướng',
      'skill_improving': 'Đang cải thiện',
      'skill_stable': 'Ổn định',
      'skill_declining': 'Suy giảm',
      'skill_elite': 'Elite',
      'skill_excellent': 'Xuất sắc',
      'skill_advanced': 'Nâng cao',
      'skill_intermediate': 'Trung bình',
      'skill_developing': 'Đang phát triển',
      'skill_needs_improvement': 'Cần cải thiện',
      'low_confidence_warning': 'Dữ liệu chưa đủ - cần thêm thông tin',
      'career_progress': 'Tiến độ sự nghiệp',
      'training_focus': 'Trọng tâm tập luyện',
      'no_skills_yet': 'Chưa có kỹ năng nào được tính',
      'calculate_skills': 'Tính kỹ năng',
      'last_updated': 'Cập nhật lần cuối',
      'daily_readiness': 'Sẵn sàng hàng ngày',
      'today_readiness': 'Tình trạng hôm nay',
      'physical_condition': 'Thể lực',
      'sleep_hours': 'Giờ ngủ',
      'energy_level': 'Mức năng lượng',
      'focus_level': 'Mức tập trung',
      'confidence_level': 'Mức tự tin',
      'stress_level': 'Mức stress',
      'mood': 'Tâm trạng',
      'physical_check': 'Kiểm tra thể chất',
      'shoulder_condition': 'Tình trạng vai',
      'arm_condition': 'Tình trạng tay',
      'session_prep': 'Chuẩn bị buổi chơi',
      'playing_location': 'Địa điểm chơi',
      'table_speed': 'Tốc độ bàn',
      'today_goal': 'Mục tiêu hôm nay',
      'how_feeling': 'Bạn cảm thấy thế nào?',
      'goal_hint': 'Bạn muốn đạt được gì hôm nay?',
      'notes_hint': 'Ghi chú thêm...',
      'location_club': 'CLB',
      'location_home': 'Nhà',
      'location_academy': 'Học viện',
      'location_tournament': 'Giải đấu',
      'table_slow': 'Chậm',
      'table_medium': 'Trung bình',
      'table_fast': 'Nhanh',
      'mood_great': 'Tuyệt vời',
      'mood_good': 'Tốt',
      'mood_okay': 'Bình thường',
      'mood_tired': 'Mệt',
      'mood_bad': 'Kém',
      'condition_excellent': 'Xuất sắc',
      'condition_good': 'Tốt',
      'condition_okay': 'Bình thường',
      'condition_tight': 'Căng',
      'condition_painful': 'Đau',
      'readiness_excellent': 'Xuất sắc',
      'readiness_good': 'Tốt',
      'readiness_moderate': 'Trung bình',
      'readiness_low': 'Thấp',
      'readiness_poor': 'Kém',
      'quick_actions': 'Thao tác nhanh',
      'start_practice': 'Bắt đầu tập',
      'start_match': 'Bắt đầu đấu',
      'continue_session': 'Tiếp tục',
      'current_equipment': 'Dụng cụ hiện tại',
      'break_cue': 'Cơ phá',
      'cue_type_playing': 'Cơ chơi',
      'cue_type_break': 'Cơ phá',
      'cue_type_jump': 'Cơ nhảy',
      'cue_type_break_jump': 'Cơ phá + nhảy',
      'cue_type_support': 'Cơ hỗ trợ',
      'add_equipment': 'Thêm cơ đầu tiên',
      'coach_insight': 'Gợi ý Huấn luyện viên',
      'weekly_trend': 'Tuần này',
      'monthly_trend': 'Tháng này',
      'recent_sessions': 'Các buổi gần đây',
      'see_all': 'Xem tất cả',
      'no_sessions_yet': 'Chưa có buổi nào',
      'log_readiness': 'Điền tình trạng hôm nay',
      'tap_to_log': 'Bấm để ghi nhận',
      'performance_score': 'Điểm Hiệu Suất',
      'break_and_run': 'Phá & Chạy',
      'session_finished': 'Buổi đã kết thúc!',
      'view_summary': 'Xem Tóm tắt',
      'select_match_type': 'Chọn Loại Trận',
      'select_session_type': 'Chọn Loại Buổi',
      'match_details': 'Chi Tiết Trận',
      'finish_match': 'Kết Thúc Trận',
      'edit_match': 'Sửa Trận',
      'delete_match': 'Xóa Trận',
      'no_racks': 'Chưa có ván nào',
      'opponent': 'Đối thủ',
      'race_to': 'Đấu đến',
      'race_to_custom': 'Đấu đến số ván tùy chọn…',
      'race_to_5': 'Đấu đến 5',
      'race_to_7': 'Đấu đến 7',
      'select_winner': 'Chọn Người Thắng',
      'match_winner': 'Người Thắng Trận',
      'you': 'Bạn',
      'winner': 'Người thắng',
      'select_as_active': 'Chọn làm Hoạt động',
      'add_cue': 'Thêm Cơ',
      'edit_cue': 'Sửa Cơ',
      'cue_name': 'Tên Cơ',
      'details': 'Chi tiết',
      'cue_added': 'Đã thêm cơ thành công',
      'cue_updated': 'Đã cập nhật cơ thành công',
      'cue_deleted': 'Đã xóa cơ',
      'delete_cue_confirm': 'Xóa cơ',
      'coach': 'Huấn luyện viên',
      'overview': 'Tổng quan',
      'insights': 'Phân tích',
      'ask': 'Hỏi',
      'ask_coach_hint': 'Hỏi huấn luyện viên...',
      'no_insights': 'Chưa có phân tích',
      'play_sessions_for_insights':
          'Chơi thêm buổi để nhận phân tích cá nhân hóa',
      'training_advice': 'Lời Khuyên Tập Luyện',
      'strengths': 'Điểm Mạnh',
      'weaknesses': 'Điểm Cần Cải Thiện',
      'coach_summary': 'Tóm Tắt Huấn Luyện Viên',
      'recommended_drill': 'Bài Tập Đề Xuất',
      'definition': 'Định nghĩa',
      'calculation': 'Cách tính',
      'target': 'Mục tiêu',
      'advice': 'Lời khuyên',
      'trend': 'Xu hướng',
      'current_value': 'Giá trị hiện tại',
      'total_wins': 'Tổng Thắng',
      'total_losses': 'Tổng Thua',
      'win_rate': 'Tỷ lệ Thắng',
      'shot_accuracy': 'Độ chính xác',
      'career_accuracy': 'Độ Chính Xác Sự Nghiệp',
      'recent_performance': 'Hiệu Suất Gần Đây',
      'improvement_tips': 'Mẹo Cải Thiện',
      'weekly_performance': 'Hiệu Suất Tuần',
      'accuracy_trend': 'Xu Hướng Độ Chính Xác',
      'close': 'Đóng',
      'total_events': 'Tổng Sự Kiện',
      'no_players_yet': 'Chưa có người chơi',
      'create_first_player': 'Tạo người chơi đầu tiên để bắt đầu',
      'add_player': 'Thêm Người Chơi',
      'delete_player': 'Xóa Người Chơi',
      'are_you_sure_delete': 'Bạn có chắc muốn xóa',
      'skill_level': 'Cấp độ Kỹ năng',
      'default_equipment': 'Dụng cụ Mặc định',
      'cue_name_hint': 'ví dụ: Predator REVO',
      'select_avatar_color': 'Chọn Màu Đại diện',
      'beginner': 'Người mới',
      'intermediate': 'Trung bình',
      'advanced': 'Nâng cao',
      'expert': 'Chuyên gia',
      'professional': 'Chuyên nghiệp',
      'name_required': 'Tên là bắt buộc',
      'ghost_skill_level': 'Cấp độ Ghost',
      'ghost_challenge_won': 'Bạn Thắng!',
      'ghost_challenge_lost': 'Ghost Thắng!',
      'ghost_challenge_tie': 'Hòa!',
      'reset_challenge': 'Chơi Lại',
      'new_challenge': 'Thử Thách Mới',
      'who_won_rack': 'Ai thắng ván này?',
      'drill_progress': 'Tiến độ tập',
      'drill_complete': 'Hoàn thành bài tập!',
      'drill_instructions': 'Hướng dẫn',
      'try_again': 'Thử Lại',
      'filter_drills': 'Lọc bài tập',
      'category': 'Danh mục',
      'difficulty': 'Độ khó',
      'duration': 'Thời gian',
      'focus_areas': 'Trọng tâm',
      'clear_filters': 'Xóa lọc',
      'no_drills_found': 'Không tìm thấy bài tập',
      'adjust_filters': 'Thử điều chỉnh bộ lọc',
      'enroll_program': 'Đăng ký chương trình',
      'withdraw_program': 'Rút khỏi chương trình',
      'program_progress': 'Tiến độ chương trình',
      'current_week': 'Tuần {current}/{total}',
      'sessions_completed': '{completed}/{total} buổi',
      'upcoming_sessions': 'Các buổi tiếp theo',
      'program_overview': 'Tổng quan chương trình',
      'phases': 'Các giai đoạn',
      'total_sessions': 'Tổng buổi',
      'session_length': 'Thời lượng buổi tập',
      'week_progress': 'Tiến độ tuần {number}',
      'confirm_withdraw': 'Rút khỏi chương trình?',
      'withdraw_warning':
          'Tiến độ của bạn sẽ được lưu nhưng bạn cần bắt đầu lại.',
      'shot_type': 'Loại cú đánh',
      'shot_difficulty': 'Độ khó',
      'shot_result': 'Kết quả',
      'quick_add': 'Thêm nhanh',
      'shot_history': 'Lịch sử cú đánh',
      'clear_all_shots': 'Xóa tất cả',
      'undo_last_shot': 'Hoàn tác cú cuối',
      'made': 'Trúng',
      'missed': 'Trượt',
      'foul': 'Lỗi',
      'break': 'Phá bàn',
      'accuracy': 'Độ chính xác',
      'event_category': 'Danh mục',
      'event_type': 'Loại',
      'event_severity': 'Mức độ nghiêm trọng',
      'great_shot': 'Cú đánh hay',
      'mistake': 'Sai lầm',
      'safety_won': 'Thắng an toàn',
      'safety_lost': 'Thua an toàn',
      'dry_break': 'Phá khô',
      'mental_event': 'Tâm lý',
      'event_history': 'Lịch sử sự kiện',
      'minor': 'Nhẹ',
      'moderate': 'Trung bình',
      'significant': 'Đáng kể',
      'critical': 'Nghiêm trọng',
      'goals': 'Mục tiêu',
      'add_goal': 'Thêm mục tiêu',
      'today_goals': 'Mục tiêu hôm nay',
      'all_goals': 'Tất cả mục tiêu',
      'goal_progress': 'Tiến độ mục tiêu',
      'goals_completed': 'Mục tiêu đã hoàn thành',
      'set_goals': 'Đặt mục tiêu',
      'priority': 'Ưu tiên',
      'low': 'Thấp',
      'high': 'Cao',
      'urgent': 'Khẩn cấp',
      'completed': 'Hoàn thành',
      'abandoned': 'Đã từ bỏ',
      'overdue': 'Quá hạn',
      'days_remaining': 'Còn {days} ngày',
      'abandon_goal': 'Từ bỏ mục tiêu',
      'delete_goal': 'Xóa mục tiêu',
      'current_vs_previous': 'Hiện tại vs Trước đó',
      'skill_comparison': 'So sánh kỹ năng',
      'improvement': 'Cải thiện',
      'undo_rack': 'Hoàn tác ván cuối',
      'undo_rack_confirm': 'Hoàn tác ván cuối?',
      'undo_rack_message':
          'Điều này sẽ xóa ván #{number} và cập nhật thống kê trận đấu.',
      'rack_undone': 'Đã hoàn tác ván #{number}',
      // Dashboard
      'quick_stats': 'Thống kê nhanh',
      'today_focus': 'Trọng tâm hôm nay',
      'current_streak': 'Ngày liên tiếp',
      'weekly_hours': 'Tuần này',
      'no_skills': 'Chưa có dữ liệu kỹ năng',
      'last_matches': '10 Trận gần nhất',
      'no_matches': 'Chưa có trận nào',
      'won': 'Thắng',
      'lost': 'Thua',
      'in_progress': 'Đang diễn ra',
      'unknown_cue': 'Cơ không xác định',
      'unknown_date': 'Ngày không xác định',
      'unknown_error': 'Lỗi không xác định',
      'retry': 'Thử lại',
      'error_loading_data': 'Lỗi tải dữ liệu',
      // Session
      'view_details': 'Xem chi tiết',
      // Equipment
      'my_cue': 'Cơ của tôi',
      'please_enter_cue_name': 'Vui lòng nhập tên cơ',
      'set_as_active_cue': '{name} đã đặt làm cơ chính',
      'set_as_break_cue': '{name} đã đặt làm cơ phá',
      'set_as_jump_cue': '{name} đã đặt làm cơ nhảy',
      // Match
      'race_to_progress': 'Tiến độ đấu đến {raceTo}',
      'match_info': 'Thông tin trận',
      'started': 'Bắt đầu',
      'ended': 'Kết thúc',
      'rack_timeline': 'Dòng thời gian ván',
      'racks': 'ván',
      'record_rack_result': 'Ghi nhận kết quả ván',
      'tap_to_record_rack': 'Bấm để ghi nhận kết quả ván tiếp theo',
      'no_racks_to_undo': 'Không có ván để hoàn tác',
      'undo_rack_action': 'Hoàn tác',
      'finished': 'Đã kết thúc',
      // Statistics
      'detailed_stats': 'Thống kê chi tiết',
      'event_analysis': 'Phân tích sự kiện',
      'by_category': 'Theo danh mục:',
      'play_more_sessions_skills': 'Chơi thêm buổi để xem phân tích kỹ năng',
      'data_points': 'điểm dữ liệu',
      'performance_metrics': 'Các chỉ số hiệu suất trong khoảng theo dõi',
      'aggregated_sessions': 'Tổng hợp từ tất cả các buổi và ván',
      'improve_weekly': 'Cải thiện 5% mỗi tuần',
      'adjust_practice': 'Xem lại điều gì hiệu quả và không. Điều chỉnh trọng tâm tập phù hợp.',
      'accuracy_over_time': 'Độ chính xác đánh cơ thay đổi theo thời gian',
      'rolling_average': 'Trung bình động của tỷ lệ thành công',
      'reach_70_accuracy': 'Đạt và duy trì độ chính xác 70%+',
      'focus_alignment': 'Tập trung vào căn chỉnh và đánh cơ. Ghi lại buổi tập để xem lại.',
      'focus_position_play': 'Tập trung vào điều bi để tạo thêm cơ hội ghi điểm',
      'practice_fundamentals': 'Luyện các cú đánh cơ bản và kỹ thuật căn chỉnh',
      'play_more_sessions': 'Chơi thêm buổi để xây dựng dữ liệu nhất quán',
      'keep_up_great_work': 'Tiếp tục phát huy! Hiệu suất của bạn rất tốt.',
      'stat_not_enough_data': 'Chưa có đủ dữ liệu.',
      'stat_play_more_unlock': 'Chơi thêm trận để mở phân tích.',
      'stat_match_won': 'Trận Đã Thắng',
      'stat_avg_balls_potted': 'Trung Bình Bi Vào Lỗ',
      'stat_avg_largest_run': 'Trung Bình Chuỗi Dài Nhất',
      'stat_avg_break_success': 'Trung Bình Phá Thành Công',
      'stat_avg_confidence': 'Trung Bình Tự Tin',
      'stat_common_mistakes': 'Lỗi Thường Gặp',
      'stat_common_strengths': 'Điểm Mạnh Thường Gặp',
      'stat_coach_insight': 'Gợi Ý Huấn Luyện Viên',
      'stat_category': 'Danh Mục',
      'stat_metric': 'Chỉ Số',
      'stat_detail': 'Chi Tiết',
      'stat_recommendation': 'Đề Xuất',
      'stat_no_data': 'Không Có Dữ Liệu',
      'stat_insight_reason': 'Lý Do',
      'stat_insight_recommendation': 'Đề Xuất',
      'stat_insight_benefit': 'Lợi Ích Kỳ Vọng',
      'stat_trend_current': 'Hiện Tại',
      'stat_trend_previous': 'Trước Đó',
      'stat_trend_difference': 'Chênh Lệch',
      'stat_reason': 'Lý Do',
      'stat_expected_improvement': 'Cải Thiện Kỳ Vọng',
      'stat_common_miss_type': 'Loại Miss Thường Gặp',
      'stat_most_frequent_error': 'Lỗi Thường Xuất Hiện',
      'stat_accuracy_trend': 'Xu Hướng Độ Chính Xác',
      'stat_main_reason': 'Lý Do Chính',
      'stat_improvement_suggestion': 'Gợi Ý Cải Thiện',
      'stat_drill_down_title': 'Phân Tích Chi Tiết',
      'stat_summary': 'Tóm Tắt',
      'stat_drill_down_empty': 'Chưa có đủ dữ liệu. Chơi thêm trận để mở phân tích.',
      'stat_recommendation_source': 'Vì {reason}, đề xuất {drill}.',
      // Coach
      'analysis': 'Phân tích',
      'coach_score': 'Điểm Coach',
      'skill_score': 'Điểm Kỹ năng',
      'trend_score': 'Điểm Xu hướng',
      // Daily Readiness
      'ready_score': 'Sẵn sàng',
      'recovery_score': 'Phục hồi',
      'wrist_condition': 'Cổ tay',
      'back_condition': 'Lưng',
      // Session Summary
      'suggested': 'Đề xuất',
      // Rack
      'rack_summary': 'Tóm tắt Ván',
      'biggest_mistake': 'Sai lầm lớn nhất',
      'biggest_strength': 'Điểm mạnh lớn nhất',
      'rack_confidence': 'Mức tự tin',
      'confidence_very_low': 'Rất thấp',
      'confidence_low': 'Thấp',
      'confidence_medium': 'Trung bình',
      'confidence_high': 'Cao',
      'confidence_very_high': 'Rất cao',
      // Settings
      'system_default': 'Mặc định hệ thống',
      'measurement_cm': 'Centimet (cm)',
      'measurement_inch': 'Inch (in)',
      // Match Selection
      'select_match': 'Chọn Trận',
      'continue_match': 'Tiếp tục Trận',
      'no_sessions_to_continue': 'Không có buổi nào để tiếp tục',
      // Coach Presentation
      'coach_no_recommendations': 'Chưa có khuyến nghị. Hoàn thành thêm buổi chơi để nhận phân tích.',
      'coach_todays_focus': 'Trọng tâm hôm nay',
      'coach_primary_focus': 'Trọng tâm chính',
      'coach_secondary_focus': 'Trọng tâm phụ',
      'coach_observation': 'Vấn đề',
      'coach_evidence': 'Lý do',
      'coach_expected_improvement': 'Cải thiện mong đợi',
      'coach_recommended_drill': 'Bài tập đề xuất',
      'coach_problem': 'Vấn đề',
      'coach_reason': 'Lý do',
      'coach_benefit': 'Lợi ích kỳ vọng',
      'coach_no_training_plan': 'Chưa có kế hoạch tập luyện',
      'coach_complete_sessions_for_plan': 'Hoàn thành thêm buổi chơi để nhận kế hoạch tập luyện cá nhân',
      'coach_todays_plan': 'Kế hoạch hôm nay',
      'coach_start_training': 'Bắt đầu tập',
      'coach_drill_info': 'Thông tin bài tập',
      'coach_difficulty': 'Độ khó',
      'coach_duration': 'Thời gian',
      'coach_short_description': 'Mô tả ngắn',
      'coach_start_drill': 'Bắt đầu bài tập',
      'coach_unavailable': 'Không khả dụng',
      'coach_history_today': 'Hôm nay',
      'coach_history_yesterday': 'Hôm qua',
      'coach_history_last_7_days': '7 ngày gần nhất',
      'coach_history_last_30_days': '30 ngày gần nhất',
      'coach_history_completed': 'Hoàn thành',
      'coach_history_result': 'Kết quả',
      'coach_performance': 'Hiệu suất',
      'coach_consistency': 'Ổn định',
      'coach_confidence': 'Tự tin',
      'coach_training_distribution': 'Phân bố tập luyện',
      'coach_improvement': 'Cải thiện',
      'coach_regression': 'Suy giảm',
      'coach_equipment_analysis': 'Phân tích dụng cụ',
      'coach_match_analysis': 'Phân tích trận đấu',
      'coach_recommendation_history': 'Lịch sử khuyến nghị',
      'coach_not_enough_data': 'Chưa có đủ dữ liệu. Chơi thêm trận để mở phân tích AI.',
      'warmup': 'Khởi động',
      'cooldown': 'Hồi phục',
      'minutes_short': 'phút',
      'drills_short': 'bài tập',
      'target_score': 'điểm mục tiêu',
      'intensity_heavy': 'Tập nặng',
      'intensity_normal': 'Bình thường',
      'intensity_light': 'Tập nhẹ',
      'intensity_recovery': 'Phục hồi',
      'category_health': 'Sức khỏe',
      'category_readiness': 'Sẵn sàng',
      'category_mental': 'Tâm lý',
      'category_skill_weakness': 'Điểm yếu',
      'category_training_plan': 'Kế hoạch',
      'category_equipment': 'Dụng cụ',
      'category_recovery': 'Phục hồi',
      'category_general': 'Chung',
      // Localization
      'localization': 'Ngôn ngữ & Địa phương',
      'appearance': 'Giao diện',
    },
  };

  String get(String key) {
    // RFC-302 Task 1: never crash on a missing key. Fall back through the
    // current locale -> English -> the key itself, so an unmapped or
    // malformed key degrades to visible text instead of throwing
    // "Null check operator used on a null value".
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'vi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
