import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Pool OS',
      'dashboard': 'Dashboard',
      'session': 'Session',
      'equipment': 'Equipment',
      'player': 'Player',
      'settings': 'Settings',
      'start_session': 'Start Session',
      'finish_session': 'Finish Session',
      'add_shot': 'Add Shot',
      'add_rack': 'Add Rack',
      'add_event': 'Add Event',
      'record_shot_first': 'Record a shot first before adding an event',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'no_data': 'No data available',
      'session_type': 'Session Type',
      'practice': 'Practice',
      'match': 'Match',
      'hybrid': 'Hybrid',
      'experiment': 'Experiment',
      'session_notes': 'Session Notes',
      'player_name': 'Player Name',
      'dominant_hand': 'Dominant Hand',
      'language': 'Language',
      'measurement_system': 'Measurement System',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'left': 'Left',
      'right': 'Right',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'cm': 'cm',
      'inch': 'inch',
      'rack_win': 'Win',
      'rack_loss': 'Loss',
      'shot_made': 'Made',
      'shot_missed': 'Missed',
      'cue': 'Cue',
      'shaft': 'Shaft',
      'shaft_material': 'Shaft Material',
      'shaft_diameter': 'Shaft Diameter',
      'tip': 'Tip',
      'tip_brand': 'Tip Brand',
      'tip_hardness': 'Tip Hardness',
      'tip_size': 'Tip Size',
      'cue_type': 'Cue Type',
      'weight': 'Weight',
      'balance': 'Balance',
      'joint': 'Joint',
      'active_cue': 'Active Cue',
      'active_break_cue': 'Active Break Cue',
      'active_jump_cue': 'Active Jump Cue',
      'history': 'History',
      'position_quality': 'Position Quality',
      'perfect': 'Perfect',
      'good': 'Good',
      'playable': 'Playable',
      'recovery': 'Recovery',
      'bad': 'Bad',
      'notes': 'Notes',
      'statistics': 'Statistics',
      'career': 'Career',
      'session_history': 'Session History',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'confirm': 'Confirm',
      'warning': 'Warning',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'empty_state': 'No records yet',
      'tap_to_add': 'Tap + to add',
      'today_dashboard': 'Today Dashboard',
      'skill_dashboard': 'Skill Dashboard',
      'trend_dashboard': 'Trend Dashboard',
      'drill_library': 'Drill Library',
      'start_drill': 'Start Drill',
      'record_drill': 'Record Drill',
      'personal_best': 'Personal Best',
      'export_json': 'Export JSON',
      'export_csv': 'Export CSV',
      'backup_database': 'Backup Database',
      'coach_ai': 'Coach AI',
      'training_program': 'Training Program',
      'achievements': 'Achievements',
      'career_dashboard': 'Career Dashboard',
      'training': 'Training',
      'matches': 'Matches',
      'new_match': 'New Match',
      'no_matches_yet': 'No matches yet',
      'play_matches_to_see_stats': 'Play matches to see your win rate statistics',
      'match_history': 'Match History',
      'no_racks_yet': 'No racks yet',
      'play_racks_to_see_stats': 'Play racks to see detailed statistics',
      'rack_history': 'Rack History',
      'no_shots_yet': 'No shots yet',
      'take_shots_to_see_stats': 'Take shots to see shot statistics',
      'shots_by_type': 'Shots by Type',
      'shots_by_difficulty': 'Shots by Difficulty',
      'total_shots': 'Total Shots',
      'made_shots': 'Made',
      'missed_shots': 'Missed',
      'no_errors_recorded': 'No errors recorded',
      'great_performance': 'Great performance! Keep it up!',
      'error_by_type': 'Errors by Type',
      'error_timeline': 'Error Timeline',
      'error_count_description': 'Recorded during practice sessions',
      'no_breaks_yet': 'No breaks yet',
      'play_breaks_to_see_stats': 'Play breaks to see break statistics',
      'break_history': 'Break History',
      'total_breaks': 'Total Breaks',
      'successful_breaks': 'Successful',
      'dry_breaks': 'Dry Breaks',
      'break_scratches': 'Scratches',
      'success_rate': 'Success Rate',
      'avg_balls_pocketed': 'Avg Balls',
      'win_rate_detail': 'Win Rate Detail',
      'rack_detail': 'Rack Detail',
      'shot_statistics': 'Shot Statistics',
      'error_statistics': 'Error Statistics',
      'break_statistics': 'Break Statistics',
      'detailed_statistics': 'Detailed Statistics',
      'total_matches': 'Total Matches',
      'wins': 'Wins',
      'losses': 'Losses',
      'racks_won': 'Won',
      'racks_lost': 'Lost',
      'confidence': 'Confidence',
      'balls_run': 'Balls',
      'total_errors': 'Total Errors',
      'scratch': 'Scratch',
      'balls': 'balls',
      'run': 'Run',
      'error_loading_stats': 'Error loading statistics',
      'total_racks': 'Total Racks',
      'active': 'Active',
      'warm_up': 'Warm Up',
      'ghost_challenge': 'Ghost Challenge',
      'challenge_match': 'Challenge Match',
      'league_match': 'League Match',
      'tournament_match': 'Tournament Match',
      'practice_match': 'Practice Match',
      'drill': 'Drill',
      'sessions': 'Sessions',
      'rack_count': 'Racks',
      'shot_count': 'Shots',
      'event_count': 'Events',
      'session_duration': 'Duration',
      'notes_placeholder': 'Add notes here...',
      'performance': 'Performance',
      'best_strength': 'Best Strength',
      'balls_potted': 'Balls Potted',
      'largest_run': 'Largest Run',
      'break_success': 'Success',
      'position_error': 'Position',
      'safety_error': 'Safety',
      'kick_error': 'Kick',
      'jump_error': 'Jump',
      'easy_miss': 'Easy Miss',
      'hard_miss': 'Hard Miss',
      'select_type': 'Select type',
      'select_hand': 'Select dominant hand',
      'select_language': 'Select language',
      'select_measurement': 'Select measurement system',
      'select_theme': 'Select theme',
      'session_summary': 'Session Summary',
      'session_stats': 'Statistics',
      'delete_session': 'Delete Session',
      'duplicate_session': 'Duplicate Session',
      'are_you_sure': 'Are you sure?',
      'yes': 'Yes',
      'no': 'No',
      'conversations': 'Conversations',
      'new_conversation': 'New Conversation',
      'conversation_title_hint': 'Enter conversation title',
      'chat': 'Chat',
      'type_message': 'Type a message...',
      'send': 'Send',
      'no_messages': 'No messages yet',
      'delete_conversation': 'Delete Conversation',
      'create': 'Create',
      'skill_stroke': 'Stroke',
      'skill_stroke_desc': 'Your stroke smoothness and cue delivery',
      'skill_position': 'Position',
      'skill_position_desc': 'Position play and ball control',
      'skill_decision': 'Decision',
      'skill_decision_desc': 'Shot selection and safety play',
      'skill_pattern': 'Pattern',
      'skill_pattern_desc': 'Pattern recognition and run outs',
      'skill_break': 'Break',
      'skill_break_desc': 'Break effectiveness and ball scatter',
      'skill_safety': 'Safety',
      'skill_safety_desc': 'Safety play and leave planning',
      'skill_mental': 'Mental',
      'skill_mental_desc': 'Pressure handling and focus',
      'skill_consistency': 'Consistency',
      'skill_consistency_desc': 'Reliable performance across sessions',
      'skill_equipment': 'Equipment',
      'skill_equipment_desc': 'Adaptation to different cues and tables',
      'skill_recovery': 'Recovery',
      'skill_recovery_desc': 'Recovery after mistakes',
      'skill_radar': 'Skill Radar',
      'skill_cards': 'Skill Cards',
      'skill_timeline': 'Skill Timeline',
      'skill_heatmap': 'Skill Heatmap',
      'skill_overview': 'Skill Overview',
      'skill_confidence': 'Confidence',
      'skill_trend': 'Trend',
      'skill_improving': 'Improving',
      'skill_stable': 'Stable',
      'skill_declining': 'Declining',
      'skill_elite': 'Elite',
      'skill_excellent': 'Excellent',
      'skill_advanced': 'Advanced',
      'skill_intermediate': 'Intermediate',
      'skill_developing': 'Developing',
      'skill_needs_improvement': 'Needs Improvement',
      'low_confidence_warning': 'Low confidence - more data needed',
      'career_progress': 'Career Progress',
      'training_focus': 'Training Focus',
      'no_skills_yet': 'No skills calculated yet',
      'calculate_skills': 'Calculate Skills',
      'last_updated': 'Last updated',
      'daily_readiness': 'Daily Readiness',
      'today_readiness': "Today's Readiness",
      'physical_condition': 'Physical Condition',
      'sleep_hours': 'Sleep Hours',
      'energy_level': 'Energy Level',
      'focus_level': 'Focus Level',
      'confidence_level': 'Confidence Level',
      'stress_level': 'Stress Level',
      'mood': 'Mood',
      'physical_check': 'Physical Check',
      'shoulder_condition': 'Shoulder Condition',
      'arm_condition': 'Arm Condition',
      'session_prep': 'Session Prep',
      'playing_location': 'Playing Location',
      'table_speed': 'Table Speed',
      'today_goal': "Today's Goal",
      'how_feeling': 'How are you feeling?',
      'goal_hint': 'What do you want to achieve today?',
      'notes_hint': 'Any additional notes...',
      'location_club': 'Club',
      'location_home': 'Home',
      'location_academy': 'Academy',
      'location_tournament': 'Tournament',
      'table_slow': 'Slow',
      'table_medium': 'Medium',
      'table_fast': 'Fast',
      'mood_great': 'Great',
      'mood_good': 'Good',
      'mood_okay': 'Okay',
      'mood_tired': 'Tired',
      'mood_bad': 'Bad',
      'condition_excellent': 'Excellent',
      'condition_good': 'Good',
      'condition_okay': 'Okay',
      'condition_tight': 'Tight',
      'condition_painful': 'Painful',
      'readiness_excellent': 'Excellent',
      'readiness_good': 'Good',
      'readiness_moderate': 'Moderate',
      'readiness_low': 'Low',
      'readiness_poor': 'Poor',
      'quick_actions': 'Quick Actions',
      'start_practice': 'Start Practice',
      'start_match': 'Start Match',
      'continue_session': 'Continue',
      'current_equipment': 'Current Equipment',
      'break_cue': 'Break Cue',
      'cue_type_playing': 'Playing Cue',
      'cue_type_break': 'Break Cue',
      'cue_type_jump': 'Jump Cue',
      'cue_type_break_jump': 'Break + Jump',
      'add_equipment': 'Add your first cue',
      'coach_insight': 'Coach Insight',
      'weekly_trend': 'This Week',
      'monthly_trend': 'This Month',
      'recent_sessions': 'Recent Sessions',
      'see_all': 'See All',
      'no_sessions_yet': 'No sessions yet',
      'log_readiness': 'Log your readiness',
      'tap_to_log': 'Tap to log today\'s condition',
      'performance_score': 'Performance Score',
      'break_and_run': 'Break & Run',
      'session_finished': 'Session finished!',
      'view_summary': 'View Summary',
      'select_match_type': 'Select Match Type',
      'select_session_type': 'Select Session Type',
      'match_details': 'Match Details',
      'finish_match': 'Finish Match',
      'edit_match': 'Edit Match',
      'delete_match': 'Delete Match',
      'no_racks': 'No racks yet',
      'opponent': 'Opponent',
      'race_to': 'Race to',
      'race_to_custom': 'Custom race to…',
      // Task 02: Shot recording wizard
      'shot_intent': 'What were you trying to do?',
      'shot_type_label': 'Shot type',
      'miss_reason_label': 'What went wrong?',
      'shot_saved': 'Shot saved',
      'intent_pot': 'Pot',
      'intent_position': 'Position',
      'intent_safety': 'Safety',
      'intent_break': 'Break',
      'intent_escape': 'Escape',
      'miss_reason_aim': 'Aim',
      'miss_reason_speed': 'Speed',
      'miss_reason_position': 'Position',
      'miss_reason_english': 'English',
      'miss_reason_kick': 'Kick',
      'miss_reason_rush': 'Rushed',
      'miss_reason_nerves': 'Nerves',
      'miss_reason_bad_decision': 'Bad decision',
      // Player State System
      'pre_match_title': 'Ready to compete?',
      'pre_match_subtitle': 'A quick check before you start — different from your daily readiness.',
      'pre_match_ready': 'Ready to compete',
      'pre_match_warmed_up': 'Warmed up',
      'pre_match_hand_feel': 'Stroke / hand feel',
      'skip': 'Skip',
      'player_state_title': 'Player State',
      'player_state_warmup': 'Warm-up',
      'player_state_endurance': 'Endurance',
      'player_state_not_enough_data': 'Not enough data yet — play a few more racks.',
      'player_state_slow_starter': 'You tend to need about {racks} racks to find your form. Warm up before competitive matches.',
      'player_state_fast_starter': 'You reach your form quickly — no long warm-up needed.',
      'player_state_declines': 'Your form tends to drop around rack {rack}. Consider a short break after that point.',
      'player_state_steady': 'You hold your form steadily through the session.',
      'endurance_title': 'Endurance',
      'endurance_not_enough_data': 'Not enough data to assess yet.',
      'endurance_score': 'Endurance score',
      'endurance_steady': 'You hold your form steadily throughout play.',
      'endurance_declines': 'Your form tends to drop from around rack {rack}.',
      'endurance_cause_technical': 'The drop looks technical — aim and position, not fitness.',
      'endurance_cause_physical': 'The drop looks physical — control and speed fade with fatigue.',
      'endurance_cause_mixed': 'The drop is mixed — both technique and fitness play a part.',
      'endurance_cause_unknown': 'Not enough detail to pin down the cause.',
      'endurance_recommended_race': 'A race to {race} suits your current stamina.',
      'endurance_curve_title': 'Performance curve',
      'endurance_curve_subtitle': 'Rack quality across your most recent match.',
      'endurance_based_on': 'Based on {matches} matches, {racks} racks.',
      'endurance_error': 'Could not load endurance data.',
      'post_match_title': 'How tired are you?',
      'post_match_subtitle': 'A quick note on your fatigue after this match.',
      'fatigue_none': 'Not tired',
      'fatigue_light': 'A little tired',
      'fatigue_tired': 'Tired',
      'fatigue_exhausted': 'Very tired',
      'race_to_5': 'Race to 5',
      'race_to_7': 'Race to 7',
      'select_winner': 'Select Winner',
      'match_winner': 'Match Winner',
      'you': 'You',
      'winner': 'Winner',
      'select_as_active': 'Select as Active',
      'add_cue': 'Add Cue',
      'edit_cue': 'Edit Cue',
      'cue_name': 'Cue Name',
      'details': 'Details',
      'cue_added': 'Cue added successfully',
      'cue_updated': 'Cue updated successfully',
      'cue_deleted': 'Cue deleted',
      'delete_cue_confirm': 'Delete cue',
      'coach': 'Coach',
      'overview': 'Overview',
      'insights': 'Insights',
      'ask': 'Ask',
      'ask_coach_hint': 'Ask your coach...',
      'no_insights': 'No insights yet',
      'play_sessions_for_insights':
          'Play more sessions to get personalized insights',
      'training_advice': 'Training Advice',
      'strengths': 'Strengths',
      'weaknesses': 'Areas to Improve',
      'coach_summary': 'Coach Summary',
      'recommended_drill': 'Recommended Drill',
      'definition': 'Definition',
      'calculation': 'Calculation',
      'target': 'Target',
      'advice': 'Advice',
      'trend': 'Trend',
      'current_value': 'Current Value',
      'total_wins': 'Total Wins',
      'total_losses': 'Total Losses',
      'win_rate': 'Win Rate',
      'shot_accuracy': 'Shot Accuracy',
      'career_accuracy': 'Career Accuracy',
      'recent_performance': 'Recent Performance',
      'improvement_tips': 'Improvement Tips',
      'weekly_performance': 'Weekly Performance',
      'accuracy_trend': 'Accuracy Trend',
      'close': 'Close',
      'total_events': 'Total Events',
      'no_players_yet': 'No players yet',
      'create_first_player': 'Create your first player to get started',
      'add_player': 'Add Player',
      'delete_player': 'Delete Player',
      'are_you_sure_delete': 'Are you sure you want to delete',
      'skill_level': 'Skill Level',
      'default_equipment': 'Default Equipment',
      'cue_name_hint': 'e.g., Predator REVO',
      'select_avatar_color': 'Select Avatar Color',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'expert': 'Expert',
      'professional': 'Professional',
      'name_required': 'Name is required',
      'ghost_skill_level': 'Ghost Skill Level',
      'ghost_challenge_won': 'You Won!',
      'ghost_challenge_lost': 'Ghost Wins!',
      'ghost_challenge_tie': "It's a Tie!",
      'reset_challenge': 'Reset Challenge',
      'new_challenge': 'New Challenge',
      'who_won_rack': 'Who won this rack?',
      'drill_progress': 'Drill Progress',
      'drill_complete': 'Drill Complete!',
      'drill_instructions': 'Instructions',
      'try_again': 'Try Again',
      'filter_drills': 'Filter Drills',
      'category': 'Category',
      'difficulty': 'Difficulty',
      'duration': 'Duration',
      'focus_areas': 'Focus Areas',
      'clear_filters': 'Clear Filters',
      'no_drills_found': 'No drills found',
      'adjust_filters': 'Try adjusting your filters',
      'enroll_program': 'Enroll in Program',
      'withdraw_program': 'Withdraw from Program',
      'program_progress': 'Program Progress',
      'current_week': 'Week {current}/{total}',
      'sessions_completed': '{completed}/{total} sessions',
      'upcoming_sessions': 'Upcoming Sessions',
      'program_overview': 'Program Overview',
      'phases': 'Phases',
      'total_sessions': 'Total Sessions',
      'session_length': 'Session Length',
      'week_progress': 'Week {number} Progress',
      'confirm_withdraw': 'Withdraw from Program?',
      'withdraw_warning':
          'Your progress will be saved but you will need to restart.',
      'shot_type': 'Shot Type',
      'shot_difficulty': 'Difficulty',
      'shot_result': 'Result',
      'quick_add': 'Quick Add',
      'shot_history': 'Shot History',
      'clear_all_shots': 'Clear All',
      'undo_last_shot': 'Undo Last Shot',
      'made': 'Made',
      'missed': 'Missed',
      'foul': 'Foul',
      'break': 'Break',
      'accuracy': 'Accuracy',
      'event_category': 'Category',
      'event_type': 'Type',
      'event_severity': 'Severity',
      'great_shot': 'Great Shot',
      'mistake': 'Mistake',
      'safety_won': 'Safety Won',
      'safety_lost': 'Safety Lost',
      'dry_break': 'Dry Break',
      'mental_event': 'Mental',
      'event_history': 'Event History',
      'minor': 'Minor',
      'moderate': 'Moderate',
      'significant': 'Significant',
      'critical': 'Critical',
      'goals': 'Goals',
      'add_goal': 'Add Goal',
      'today_goals': "Today's Goals",
      'all_goals': 'All Goals',
      'goal_progress': 'Goal Progress',
      'goals_completed': 'Goals Completed',
      'set_goals': 'Set Goals',
      'priority': 'Priority',
      'low': 'Low',
      'high': 'High',
      'urgent': 'Urgent',
      'completed': 'Completed',
      'abandoned': 'Abandoned',
      'overdue': 'Overdue',
      'days_remaining': '{days} days remaining',
      'abandon_goal': 'Abandon Goal',
      'delete_goal': 'Delete Goal',
      'current_vs_previous': 'Current vs Previous',
      'skill_comparison': 'Skill Comparison',
      'improvement': 'Improvement',
      'undo_rack': 'Undo Last Rack',
      'undo_rack_confirm': 'Undo Last Rack?',
      'undo_rack_message':
          'This will remove rack #{number} and update the match stats.',
      'rack_undone': 'Rack #{number} undone',
      // Dashboard
      'quick_stats': 'Quick Stats',
      'today_focus': "Today's Focus",
      'current_streak': 'Day Streak',
      'weekly_hours': 'This Week',
      'no_skills': 'No skill data yet',
      'last_matches': 'Last 10 Matches',
      'no_matches': 'No matches yet',
      'won': 'Won',
      'lost': 'Lost',
      'in_progress': 'In Progress',
      'unknown_cue': 'Unknown Cue',
      'unknown_date': 'Unknown date',
      'unknown_error': 'Unknown error',
      'retry': 'Retry',
      'error_loading_data': 'Error loading data',
      // Session
      'view_details': 'View Details',
      // Equipment
      'my_cue': 'My Cue',
      'please_enter_cue_name': 'Please enter a cue name',
      'set_as_active_cue': '{name} set as active cue',
      'set_as_break_cue': '{name} set as break cue',
      'set_as_jump_cue': '{name} set as jump cue',
      // Match
      'race_to_progress': '{raceTo} Progress',
      'match_info': 'Match Info',
      'started': 'Started',
      'ended': 'Ended',
      'rack_timeline': 'Rack Timeline',
      'racks': 'racks',
      'record_rack_result': 'Record Rack Result',
      'tap_to_record_rack': 'Tap to record the outcome of the next rack',
      'no_racks_to_undo': 'No racks to undo',
      'undo_rack_action': 'Undo',
      'finished': 'Finished',
      // Statistics
      'detailed_stats': 'Detailed Stats',
      'event_analysis': 'Event Analysis',
      'by_category': 'By Category:',
      'play_more_sessions_skills': 'Play more sessions to see your skill analysis',
      'data_points': 'data points',
      'performance_metrics': 'Your performance metrics over the tracked period',
      'aggregated_sessions': 'Aggregated from all sessions and racks',
      'improve_weekly': 'Improve by 5% each week',
      'adjust_practice': "Review what worked and what didn't. Adjust practice focus accordingly.",
      'accuracy_over_time': 'How your shot-making accuracy has changed over time',
      'rolling_average': 'Rolling average of shot success rate',
      'reach_70_accuracy': 'Reach and maintain 70%+ accuracy',
      'focus_alignment': 'Focus on alignment and cue delivery. Record your practice sessions to review.',
      'focus_position_play': 'Focus on position play to create more scoring opportunities',
      'practice_fundamentals': 'Practice fundamental shots and alignment techniques',
      'play_more_sessions': 'Play more sessions to build consistent data',
      'keep_up_great_work': 'Keep up the great work! Your performance is excellent.',
      'stat_not_enough_data': 'Not enough data yet.',
      'stat_play_more_unlock': 'Play more matches to unlock analysis.',
      'stat_match_won': 'Matches Won',
      'stat_avg_balls_potted': 'Average Balls Potted',
      'stat_avg_largest_run': 'Average Largest Run',
      'stat_avg_break_success': 'Average Break Success',
      'stat_avg_confidence': 'Average Confidence',
      'stat_common_mistakes': 'Common Mistakes',
      'stat_common_strengths': 'Common Strengths',
      'stat_coach_insight': 'Coach Insight',
      'stat_category': 'Category',
      'stat_metric': 'Metric',
      'stat_detail': 'Detail',
      'stat_recommendation': 'Recommendation',
      'stat_no_data': 'No Data',
      'stat_insight_reason': 'Reason',
      'stat_insight_recommendation': 'Recommendation',
      'stat_insight_benefit': 'Expected Benefit',
      'stat_trend_current': 'Current',
      'stat_trend_previous': 'Previous',
      'stat_trend_difference': 'Difference',
      'stat_reason': 'Reason',
      'stat_expected_improvement': 'Expected Improvement',
      'stat_common_miss_type': 'Common Miss Type',
      'stat_most_frequent_error': 'Most Frequent Error',
      'stat_accuracy_trend': 'Accuracy Trend',
      'stat_main_reason': 'Main Reason',
      'stat_improvement_suggestion': 'Improvement Suggestion',
      'stat_drill_down_title': 'Drill-down Analysis',
      'stat_summary': 'Summary',
      'stat_drill_down_empty': 'Not enough data yet. Play more matches to unlock analysis.',
      'stat_recommendation_source': 'Because {reason}, recommend {drill}.',
      // Coach
      'analysis': 'Analysis',
      'coach_score': 'Coach Score',
      'skill_score': 'Skill Score',
      'trend_score': 'Trend Score',
      // Daily Readiness
      'ready_score': 'Ready',
      'recovery_score': 'Recovery',
      'wrist_condition': 'Wrist',
      'back_condition': 'Back',
      // Session Summary
      'suggested': 'Suggested',
      // Rack
      'rack_summary': 'Rack Summary',
      'biggest_mistake': 'Biggest Mistake',
      'biggest_strength': 'Biggest Strength',
      'rack_confidence': 'Confidence',
      'confidence_very_low': 'Very Low',
      'confidence_low': 'Low',
      'confidence_medium': 'Medium',
      'confidence_high': 'High',
      'confidence_very_high': 'Very High',
      // Settings
      'system_default': 'System Default',
      'measurement_cm': 'Centimeters (cm)',
      'measurement_inch': 'Inches (in)',
      // Match Selection
      'select_match': 'Select Match',
      'continue_match': 'Continue Match',
      'no_sessions_to_continue': 'No sessions to continue',
      // Coach Presentation
      'coach_no_recommendations': 'No recommendations yet. Complete more sessions for analysis.',
      'coach_todays_focus': "Today's Focus",
      'coach_primary_focus': 'Primary Focus',
      'coach_secondary_focus': 'Secondary Focus',
      'coach_observation': 'Problem',
      'coach_evidence': 'Reason',
      'coach_expected_improvement': 'Expected Improvement',
      'coach_recommended_drill': 'Recommended Drills',
      'coach_problem': 'Problem',
      'coach_reason': 'Reason',
      'coach_benefit': 'Expected Benefit',
      'coach_no_training_plan': 'No training plan yet',
      'coach_complete_sessions_for_plan': 'Complete more sessions to receive personalized training plans',
      'coach_todays_plan': "Today's Plan",
      'coach_start_training': 'Start Training',
      'coach_drill_info': 'Drill Info',
      'coach_difficulty': 'Difficulty',
      'coach_duration': 'Duration',
      'coach_short_description': 'Short Description',
      'coach_start_drill': 'Start Drill',
      'coach_unavailable': 'Unavailable',
      'coach_history_today': 'Today',
      'coach_history_yesterday': 'Yesterday',
      'coach_history_last_7_days': 'Last 7 Days',
      'coach_history_last_30_days': 'Last 30 Days',
      'coach_history_completed': 'Completed',
      'coach_history_result': 'Result',
      'coach_performance': 'Performance',
      'coach_consistency': 'Consistency',
      'coach_confidence': 'Confidence',
      'coach_training_distribution': 'Training Distribution',
      'coach_improvement': 'Improvement',
      'coach_regression': 'Regression',
      'coach_equipment_analysis': 'Equipment Analysis',
      'coach_match_analysis': 'Match Analysis',
      'coach_recommendation_history': 'Recommendation History',
      'coach_not_enough_data': 'Not enough data yet. Play more matches to unlock AI analysis.',
      'warmup': 'Warmup',
      'cooldown': 'Cooldown',
      'minutes_short': 'min',
      'drills_short': 'drills',
      'target_score': 'target score',
      'intensity_heavy': 'Heavy',
      'intensity_normal': 'Normal',
      'intensity_light': 'Light',
      'intensity_recovery': 'Recovery',
      'category_health': 'Health',
      'category_readiness': 'Readiness',
      'category_mental': 'Mental',
      'category_skill_weakness': 'Weakness',
      'category_training_plan': 'Plan',
      'category_equipment': 'Equipment',
      'category_recovery': 'Recovery',
      'category_general': 'General',
      // Task 12 — Data Center
      'dc_title': 'Data Center',
      'dc_section_backup': 'Backup & Restore',
      'dc_section_export': 'Export',
      'dc_section_info': 'Database info',
      'dc_section_maintenance': 'Maintenance',
      'dc_backup_desc': 'Save a full backup of all your data to a file.',
      'dc_create_backup': 'Create backup',
      'dc_backup_created': 'Backup created',
      'dc_no_backups': 'No backups yet.',
      'dc_rows': 'rows',
      'dc_restore': 'Restore',
      'dc_restore_confirm_title': 'Restore this backup?',
      'dc_restore_confirm_body':
          'This replaces ALL current data with the backup ({rows} rows). This cannot be undone.',
      'dc_restore_ok': 'Restored {rows} rows.',
      'dc_export_desc': 'Export a module as JSON or CSV.',
      'dc_export_ok': 'Export saved',
      'dc_export_matches': 'Match history',
      'dc_export_training': 'Training',
      'dc_export_goals': 'Goals',
      'dc_export_equipment': 'Equipment',
      'dc_export_shots': 'Shots',
      'dc_db_version': 'Schema version',
      'dc_backup_format': 'Backup format',
      'dc_db_size': 'Database size',
      'dc_verify': 'Verify integrity',
      'dc_verify_desc': 'Check the database for corruption.',
      'dc_verify_ok': 'Integrity check passed.',
      'dc_verify_fail': 'Integrity check found problems.',
      'dc_compact': 'Compact database',
      'dc_compact_desc': 'Reclaim unused space (VACUUM).',
      'dc_compact_ok': 'Database compacted.',
      'dc_clear_temp': 'Clear temporary files',
      'dc_clear_temp_desc': 'Remove generated export files.',
      'dc_clear_temp_ok': 'Removed {n} files.',
      'dc_err_format': 'Backup format is newer than this app version.',
      'dc_err_schema': 'Backup is from a different database version.',
      'dc_err_restore': 'Restore failed. Your data was not changed.',
      'dc_err_parse': 'Could not read the backup file.',
      // Task 13 — Tournament & League
      'tnmt_title': 'Tournaments',
      'tnmt_new': 'New tournament',
      'tnmt_create': 'Create tournament',
      'tnmt_name': 'Tournament name',
      'tnmt_name_required': 'Please enter a name.',
      'tnmt_type': 'Format',
      'tnmt_location': 'Location',
      'tnmt_start_date': 'Start date',
      'tnmt_end_date': 'End date',
      'tnmt_notes': 'Notes',
      'tnmt_load_error': 'Could not load tournaments.',
      'tnmt_not_found': 'Tournament not found.',
      'tnmt_empty_title': 'No tournaments yet',
      'tnmt_empty_body': 'Create a tournament to organize matches into a bracket, league or round robin.',
      'tnmt_delete_title': 'Delete this tournament?',
      'tnmt_delete_body': 'The bracket and participants are removed. Recorded matches are kept.',
      'tnmt_type_singleElimination': 'Single elimination',
      'tnmt_type_singleElimination_desc': 'Lose once and you are out.',
      'tnmt_type_doubleElimination': 'Double elimination',
      'tnmt_type_doubleElimination_desc': 'A loss drops you to the losers bracket.',
      'tnmt_type_roundRobin': 'Round robin',
      'tnmt_type_roundRobin_desc': 'Everyone plays everyone once.',
      'tnmt_type_league': 'League',
      'tnmt_type_league_desc': 'Round robin ranked by points.',
      'tnmt_status_upcoming': 'Upcoming',
      'tnmt_status_active': 'Active',
      'tnmt_status_completed': 'Completed',
      'tnmt_tab_participants': 'Participants',
      'tnmt_tab_bracket': 'Bracket',
      'tnmt_tab_standings': 'Standings',
      'tnmt_tab_stats': 'Statistics',
      'tnmt_add_participant': 'Add participant',
      'tnmt_no_participants': 'No participants yet.',
      'tnmt_pick_player': 'Pick a player',
      'tnmt_add_guest': 'Add a guest',
      'tnmt_guest_name': 'Guest name',
      'tnmt_guest': 'Guest',
      'tnmt_player': 'Player',
      'tnmt_set_seed': 'Set seed',
      'tnmt_seed_hint': 'Seed number (1 = top). Leave empty to clear.',
      'tnmt_generate_bracket': 'Generate bracket',
      'tnmt_bracket_created': 'Bracket created.',
      'tnmt_bracket_locked': 'Bracket already has results — delete them before re-seeding.',
      'tnmt_no_bracket': 'No bracket yet. Add at least 2 participants and generate the bracket.',
      'tnmt_tbd': 'TBD',
      'tnmt_tap_to_record': 'Tap to record result',
      'tnmt_record_result': 'Record result',
      'tnmt_racks': 'racks',
      'tnmt_round': 'Round',
      'tnmt_round_final': 'Final',
      'tnmt_round_semi': 'Semifinal',
      'tnmt_round_quarter': 'Quarterfinal',
      'tnmt_no_standings': 'No results yet. Standings appear after the first match.',
      'tnmt_col_rank': '#',
      'tnmt_col_player': 'Player',
      'tnmt_col_w': 'W',
      'tnmt_col_l': 'L',
      'tnmt_col_rackdiff': 'Rack +/-',
      'tnmt_col_pts': 'Pts',
      'tnmt_stat_participants': 'Participants',
      'tnmt_stat_fixtures': 'Total fixtures',
      'tnmt_stat_played': 'Played',
      'tnmt_stat_remaining': 'Ready to play',
      'tnmt_stat_racks': 'Racks recorded',
      'tnmt_stat_empty': 'Statistics appear once matches are recorded.',
      'tnmt_champion': 'Champion',
      // Task 14 — Club & Community
      'club_title': 'Clubs',
      'club_new': 'New club',
      'club_create': 'Create club',
      'club_name': 'Club name',
      'club_name_required': 'Please enter a name.',
      'club_location': 'Location',
      'club_description': 'Description',
      'club_manager': 'Manager',
      'club_load_error': 'Could not load clubs.',
      'club_not_found': 'Club not found.',
      'club_empty_title': 'No clubs yet',
      'club_empty_body': 'Create a club to group players, track an internal ranking and run club events.',
      'club_delete_title': 'Delete this club?',
      'club_delete_body': 'The club and its members are removed. Linked matches, trainings and tournaments are kept.',
      'club_role_owner': 'Owner',
      'club_role_admin': 'Admin',
      'club_role_member': 'Member',
      'club_guest': 'Guest',
      'club_invited': 'Invited',
      'club_tab_members': 'Members',
      'club_tab_ranking': 'Ranking',
      'club_tab_leaderboard': 'Leaderboard',
      'club_tab_stats': 'Statistics',
      'club_tab_history': 'History',
      'club_no_members': 'No members yet.',
      'club_add_member': 'Add member',
      'club_pick_player': 'Pick a player',
      'club_add_guest': 'Add a guest',
      'club_as_invite': 'Add as invite (not confirmed yet)',
      'club_guest_name': 'Guest name',
      'club_confirm_invite': 'Confirm invite',
      'club_no_ranking': 'No ranking yet. Link club matches to build the ranking.',
      'club_col_rank': '#',
      'club_col_member': 'Member',
      'club_col_played': 'P',
      'club_col_w': 'W',
      'club_col_winrate': 'Win %',
      'club_col_streak': 'Streak',
      'club_col_pts': 'Pts',
      'club_pts_short': 'pts',
      'club_period_week': 'Week',
      'club_period_month': 'Month',
      'club_period_year': 'Year',
      'club_no_leaderboard': 'No matches in this period.',
      'club_stat_matches': 'Total matches',
      'club_stat_racks': 'Total racks',
      'club_stat_training': 'Total training time',
      'club_stat_most_active': 'Most active',
      'club_stat_most_wins': 'Most wins',
      'club_stat_most_improved': 'Most improved',
      'club_stat_empty': 'Statistics appear once club matches are linked.',
      'club_hist_matches': 'Club matches',
      'club_hist_trainings': 'Club trainings',
      'club_hist_tournaments': 'Club tournaments',
      'club_hist_empty': 'Nothing linked yet.',
      'club_unlink': 'Remove link',
      // Task 11 — Player Timeline & Career
      'career_title': 'Timeline & Career',
      'career_summary_title': 'Career summary',
      'career_since': 'Journey length',
      'career_days': 'days',
      'career_matches_won': 'Matches won',
      'career_goals_done': 'Goals done',
      'career_equipment_used': 'Equipment used',
      'career_empty': 'No history yet. Play a session to start your journey.',
      'career_no_filtered': 'No events match this filter.',
      'career_filter_all': 'All',
      'career_filter_session': 'Session',
      'career_filter_match': 'Match',
      'career_filter_goal': 'Goal',
      'career_filter_achievement': 'Achievement',
      'career_filter_equipment': 'Equipment',
      'career_filter_training': 'Training',
      'career_match_win': 'Match won',
      'career_match_loss': 'Match lost',
      'career_race': 'Race to',
      'career_equipment_added': 'New equipment',
      'career_training_session': 'Training session',
      'career_goal_completed': 'Goal completed',
      'career_achievement_unlocked': 'Achievement unlocked',
      'career_session_practice': 'Practice session',
      'career_session_match': 'Match session',
      'career_session_started': 'Session started',
      // Task 10 — Goal & Progress Center
      'gc_title': 'Goal Center',
      'gc_section_goals': 'Goals',
      'gc_section_achievements': 'Achievements',
      'gc_section_streaks': 'Streaks',
      'gc_section_milestones': 'Milestones',
      'gc_new_goal': 'New goal',
      'gc_goal_title': 'Goal name',
      'gc_metric': 'What to track',
      'gc_target_amount': 'Target amount',
      'gc_target_amount_help': 'How many more from now',
      'gc_target_percent': 'Target rate',
      'gc_target_percent_help': 'Success rate to reach',
      'gc_note_optional': 'Note (optional)',
      'gc_title_required': 'Please enter a goal name',
      'gc_amount_invalid': 'Enter a valid target',
      'gc_no_goals': 'No goals yet. Tap + to create one.',
      'gc_goal_done': 'Done',
      'gc_default_badge': 'Default',
      'gc_new': 'NEW',
      'gc_delete_goal': 'Delete goal',
      'gc_delete_goal_confirm': 'This removes the goal. Your recorded data is not affected.',
      'gc_notice_progress': '{goal}: only {percent}% away from your goal.',
      'gc_notice_done': 'You completed: {goal}!',
      // Goal metrics
      'gc_metric_matches_won': 'Matches won',
      'gc_metric_break_and_runs': 'Break & runs',
      'gc_metric_long_pot_rate': 'Long pot rate',
      'gc_metric_stop_shot_rate': 'Stop shot rate',
      'gc_metric_total_shots': 'Total shots',
      'gc_metric_total_matches': 'Total matches',
      'gc_metric_total_racks': 'Total racks',
      'gc_metric_practice_hours': 'Practice hours',
      'gc_metric_scratch_free_matches': 'Scratch-free matches',
      'gc_metric_training_day_streak': 'Training day streak',
      // Default goals
      'gc_default_first_bnr': 'First break & run',
      'gc_default_long_pot_70': 'Long pot over 70%',
      'gc_default_stop_shot_80': 'Stop shot over 80%',
      'gc_default_win_10': 'Win 10 matches',
      'gc_default_scratch_free_10': 'No scratch in 10 matches',
      // Achievements
      'gc_ach_first_match_win': 'First match win',
      'gc_ach_first_match_win_desc': 'Win your first match',
      'gc_ach_first_bnr': 'First break & run',
      'gc_ach_first_bnr_desc': 'Break and run out a rack',
      'gc_ach_win_streak_5': '5-win streak',
      'gc_ach_win_streak_5_desc': 'Win 5 matches in a row',
      'gc_ach_shots_1000': '1,000 shots',
      'gc_ach_shots_1000_desc': 'Record 1,000 shots',
      'gc_ach_matches_100': '100 matches',
      'gc_ach_matches_100_desc': 'Play 100 matches',
      'gc_ach_long_pot_70': 'Long pot 70%',
      'gc_ach_long_pot_70_desc': 'Reach a 70% long pot rate',
      // Streaks
      'gc_streak_train_7': 'Practice 7 days',
      'gc_streak_train_7_desc': '7 consecutive practice days',
      'gc_streak_train_10': 'Practice 10 days',
      'gc_streak_train_10_desc': '10 consecutive practice days',
      'gc_streak_scratch_free_10': 'Scratch-free 10',
      'gc_streak_scratch_free_10_desc': '10 matches with no scratch',
      // Milestones
      'gc_mile_matches_100': '100 matches',
      'gc_mile_matches_100_desc': 'Reach 100 matches played',
      'gc_mile_racks_500': '500 racks',
      'gc_mile_racks_500_desc': 'Reach 500 racks played',
      'gc_mile_shots_10000': '10,000 shots',
      'gc_mile_shots_10000_desc': 'Reach 10,000 shots recorded',
      'gc_mile_hours_100': '100 hours',
      'gc_mile_hours_100_desc': 'Reach 100 hours of play',
      // Task 09 — Training Center
      'training_center_title': 'Training Center',
      'tc_start_session': 'Start session',
      'tc_progress': 'Progress',
      'tc_custom_drill': 'Custom drill',
      'tc_categories': 'Categories',
      'tc_recent': 'Recent',
      'tc_load_error': 'Could not load drills.',
      'tc_no_drills': 'No drills yet.',
      'tc_custom_drill_title': 'New custom drill',
      'tc_drill_name': 'Drill name',
      'tc_drill_name_hint': 'e.g. Long straight pot',
      'tc_name_required': 'Please enter a name.',
      'tc_category': 'Category',
      'tc_target_reps': 'Target reps',
      'tc_reps_invalid': 'Enter a number greater than 0.',
      'tc_success_criteria': 'Success condition (optional)',
      'tc_success_criteria_hint': 'How do you count a success?',
      'tc_save': 'Save',
      'tc_saved': 'Saved.',
      'tc_progress_title': 'Progress',
      'tc_progress_empty': 'No practice history yet. Run a session to see progress.',
      'tc_prev': 'Previous',
      'tc_current': 'Current',
      'tc_progress_need_more': 'Not enough data to compare yet.',
      'tc_session_title': 'Training session',
      'tc_add_drill': 'Add drill',
      'tc_session_empty': 'Add a drill to start recording hits and misses.',
      'tc_target': 'Target',
      'tc_miss': 'Miss',
      'tc_hit': 'Hit',
      'tc_undo': 'Undo last',
      'tc_pick_drill': 'Pick a drill',
      'tc_search_hint': 'Search drills',
    },
    'vi': {
      'app_name': 'Pool OS',
      'dashboard': 'Trang chủ',
      'session': 'Buổi chơi',
      'equipment': 'Cơ',
      'player': 'Người chơi',
      'settings': 'Cài đặt',
      'start_session': 'Bắt đầu buổi',
      'finish_session': 'Kết thúc buổi',
      'add_shot': 'Thêm cú đánh',
      'add_rack': 'Thêm ván',
      'add_event': 'Thêm sự kiện',
      'record_shot_first': 'Ghi một cú đánh trước khi thêm sự kiện',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'edit': 'Sửa',
      'today': 'Hôm nay',
      'yesterday': 'Hôm qua',
      'no_data': 'Chưa có dữ liệu',
      'session_type': 'Loại buổi',
      'practice': 'Luyện tập',
      'match': 'Đấu',
      'hybrid': 'Kết hợp',
      'experiment': 'Thử nghiệm',
      'session_notes': 'Ghi chú buổi',
      'player_name': 'Tên người chơi',
      'dominant_hand': 'Tay thuận',
      'language': 'Ngôn ngữ',
      'measurement_system': 'Đơn vị đo',
      'theme': 'Giao diện',
      'dark_mode': 'Tối',
      'light_mode': 'Sáng',
      'left': 'Trái',
      'right': 'Phải',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'cm': 'cm',
      'inch': 'inch',
      'rack_win': 'Thắng',
      'rack_loss': 'Thua',
      'shot_made': 'Đánh trúng',
      'shot_missed': 'Trượt',
      'cue': 'Cơ',
      'shaft': 'Can',
      'shaft_material': 'Chất liệu cần',
      'shaft_diameter': 'Đường kính cần',
      'tip': 'Đầu cơ',
      'tip_brand': 'Thương hiệu đầu cơ',
      'tip_hardness': 'Độ cứng đầu cơ',
      'tip_size': 'Kích thước đầu cơ',
      'cue_type': 'Loại cơ',
      'weight': 'Trọng lượng',
      'balance': 'Cân bằng',
      'joint': 'Khớp',
      'active_cue': 'Cơ đang dùng',
      'active_break_cue': 'Cơ phá đang dùng',
      'history': 'Lịch sử',
      'position_quality': 'Chất lượng điều bi',
      'perfect': 'Hoàn hảo',
      'good': 'Tốt',
      'playable': 'Chơi được',
      'recovery': 'Cứu',
      'bad': 'Xấu',
      'notes': 'Ghi chú',
      'statistics': 'Thống kê',
      'career': 'Sự nghiệp',
      'session_history': 'Lịch sử buổi',
      'back': 'Quay lại',
      'next': 'Tiếp',
      'done': 'Xong',
      'confirm': 'Xác nhận',
      'warning': 'Cảnh báo',
      'error': 'Lỗi',
      'success': 'Thành công',
      'loading': 'Đang tải...',
      'empty_state': 'Chưa có dữ liệu',
      'tap_to_add': 'Bấm + để thêm',
      'today_dashboard': 'Hôm nay',
      'skill_dashboard': 'Kỹ năng',
      'trend_dashboard': 'Xu hướng',
      'drill_library': 'Thư viện bài tập',
      'start_drill': 'Bắt đầu tập',
      'record_drill': 'Ghi lại',
      'personal_best': 'Kỷ lục cá nhân',
      'export_json': 'Xuất JSON',
      'export_csv': 'Xuất CSV',
      'backup_database': 'Sao lưu',
      'coach_ai': 'Huấn luyện viên AI',
      'training_program': 'Chương trình tập',
      'achievements': 'Thành tích',
      'career_dashboard': 'Sự nghiệp',
      'training': 'Tập luyện',
      'matches': 'Trận đấu',
      'new_match': 'Trận mới',
      'no_matches_yet': 'Chưa có trận nào',
      'play_matches_to_see_stats': 'Chơi các trận để xem thống kê tỷ lệ thắng',
      'match_history': 'Lịch sử trận đấu',
      'no_racks_yet': 'Chưa có ván nào',
      'play_racks_to_see_stats': 'Chơi các ván để xem thống kê chi tiết',
      'rack_history': 'Lịch sử ván',
      'no_shots_yet': 'Chưa có cú đánh nào',
      'take_shots_to_see_stats': 'Đánh các cú để xem thống kê',
      'shots_by_type': 'Cú đánh theo loại',
      'shots_by_difficulty': 'Cú đánh theo độ khó',
      'total_shots': 'Tổng cú đánh',
      'made_shots': 'Đánh trúng',
      'missed_shots': 'Đánh trượt',
      'no_errors_recorded': 'Không có lỗi nào được ghi',
      'great_performance': 'Xuất sắc! Tiếp tục phát huy!',
      'error_by_type': 'Lỗi theo loại',
      'error_timeline': 'Dòng thời gian lỗi',
      'error_count_description': 'Được ghi trong buổi tập',
      'no_breaks_yet': 'Chưa có break nào',
      'play_breaks_to_see_stats': 'Chơi break để xem thống kê',
      'break_history': 'Lịch sử break',
      'total_breaks': 'Tổng Break',
      'successful_breaks': 'Thành công',
      'dry_breaks': 'Break khô',
      'break_scratches': 'Scratch',
      'success_rate': 'Tỷ lệ thành công',
      'avg_balls_pocketed': 'TB Bóng',
      'win_rate_detail': 'Chi tiết tỷ lệ thắng',
      'rack_detail': 'Chi tiết ván',
      'shot_statistics': 'Thống kê cú đánh',
      'error_statistics': 'Thống kê lỗi',
      'break_statistics': 'Thống kê Break',
      'detailed_statistics': 'Thống kê chi tiết',
      'total_matches': 'Tổng trận',
      'wins': 'Thắng',
      'losses': 'Thua',
      'racks_won': 'Thắng',
      'racks_lost': 'Thua',
      'confidence': 'Tự tin',
      'balls_run': 'Bóng',
      'total_errors': 'Tổng lỗi',
      'scratch': 'Scratch',
      'balls': 'bóng',
      'run': 'Chạy',
      'error_loading_stats': 'Lỗi tải thống kê',
      'total_racks': 'Tổng ván',
      'active': 'Đang chơi',
      'warm_up': 'Khởi động',
      'ghost_challenge': 'Đấu ma',
      'challenge_match': 'Đấu thách đấu',
      'league_match': 'Đấu giải',
      'tournament_match': 'Đấu giải đấu',
      'practice_match': 'Đấu tập',
      'drill': 'Bài tập',
      'sessions': 'Buổi chơi',
      'rack_count': 'Ván',
      'shot_count': 'Cú đánh',
      'event_count': 'Sự kiện',
      'session_duration': 'Thời gian',
      'notes_placeholder': 'Thêm ghi chú...',
      'performance': 'Hiệu suất',
      'best_strength': 'Điểm mạnh',
      'balls_potted': 'Bi vào lỗ',
      'largest_run': 'Chuỗi dài nhất',
      'break_success': 'Thành công',
      'position_error': 'Vị trí',
      'safety_error': 'An toàn',
      'kick_error': 'Đá bi',
      'jump_error': 'Nhảy',
      'easy_miss': 'Sai dễ',
      'hard_miss': 'Sai khó',
      'select_type': 'Chọn loại',
      'select_hand': 'Chọn tay thuận',
      'select_language': 'Chọn ngôn ngữ',
      'select_measurement': 'Chọn đơn vị đo',
      'select_theme': 'Chọn giao diện',
      'session_summary': 'Tóm tắt buổi',
      'session_stats': 'Thống kê',
      'delete_session': 'Xóa buổi',
      'duplicate_session': 'Nhân bản buổi',
      'are_you_sure': 'Bạn có chắc?',
      'yes': 'Có',
      'no': 'Không',
      'conversations': 'Trò truyện',
      'new_conversation': 'Cuộc trò truyện mới',
      'conversation_title_hint': 'Nhập tiêu đề cuộc trò truyện',
      'chat': 'Trò truyện',
      'type_message': 'Nhập tin nhắn...',
      'send': 'Gửi',
      'no_messages': 'Chưa có tin nhắn',
      'delete_conversation': 'Xóa cuộc trò truyện',
      'create': 'Tạo',
      'skill_stroke': 'Đánh cơ',
      'skill_stroke_desc': 'Độ mượt mà của cú đánh',
      'skill_position': 'Điều bi',
      'skill_position_desc': 'Kiểm soát vị trí và bi',
      'skill_decision': 'Quyết định',
      'skill_decision_desc': 'Chọn cú đánh và chơi an toàn',
      'skill_pattern': 'Quỹ đạo',
      'skill_pattern_desc': 'Nhận diện quỹ đạo và chạy bàn',
      'skill_break': 'Phá bàn',
      'skill_break_desc': 'Hiệu quả phá bàn',
      'skill_safety': 'An toàn',
      'skill_safety_desc': 'Chơi an toàn và lên kế hoạch',
      'skill_mental': 'Tâm lý',
      'skill_mental_desc': 'Xử lý áp lực và tập trung',
      'skill_consistency': 'Ổn định',
      'skill_consistency_desc': 'Thành tích ổn định qua các buổi',
      'skill_equipment': 'Công cụ',
      'skill_equipment_desc': 'Thích nghi với cơ và bàn khác nhau',
      'skill_recovery': 'Phục hồi',
      'skill_recovery_desc': 'Khắc phục sau sai lầm',
      'skill_radar': 'Radar Kỹ năng',
      'skill_cards': 'Thẻ Kỹ năng',
      'skill_timeline': 'Dòng thời gian',
      'skill_heatmap': 'Bản đồ nhiệt',
      'skill_overview': 'Tổng quan',
      'skill_confidence': 'Độ tin cậy',
      'skill_trend': 'Xu hướng',
      'skill_improving': 'Đang cải thiện',
      'skill_stable': 'Ổn định',
      'skill_declining': 'Suy giảm',
      'skill_elite': 'Elite',
      'skill_excellent': 'Xuất sắc',
      'skill_advanced': 'Nâng cao',
      'skill_intermediate': 'Trung bình',
      'skill_developing': 'Đang phát triển',
      'skill_needs_improvement': 'Cần cải thiện',
      'low_confidence_warning': 'Dữ liệu chưa đủ - cần thêm thông tin',
      'career_progress': 'Tiến độ sự nghiệp',
      'training_focus': 'Trọng tâm tập luyện',
      'no_skills_yet': 'Chưa có kỹ năng nào được tính',
      'calculate_skills': 'Tính kỹ năng',
      'last_updated': 'Cập nhật lần cuối',
      'daily_readiness': 'Sẵn sàng hàng ngày',
      'today_readiness': 'Tình trạng hôm nay',
      'physical_condition': 'Thể lực',
      'sleep_hours': 'Giờ ngủ',
      'energy_level': 'Mức năng lượng',
      'focus_level': 'Mức tập trung',
      'confidence_level': 'Mức tự tin',
      'stress_level': 'Mức stress',
      'mood': 'Tâm trạng',
      'physical_check': 'Kiểm tra thể chất',
      'shoulder_condition': 'Tình trạng vai',
      'arm_condition': 'Tình trạng tay',
      'session_prep': 'Chuẩn bị buổi chơi',
      'playing_location': 'Địa điểm chơi',
      'table_speed': 'Tốc độ bàn',
      'today_goal': 'Mục tiêu hôm nay',
      'how_feeling': 'Bạn cảm thấy thế nào?',
      'goal_hint': 'Bạn muốn đạt được gì hôm nay?',
      'notes_hint': 'Ghi chú thêm...',
      'location_club': 'CLB',
      'location_home': 'Nhà',
      'location_academy': 'Học viện',
      'location_tournament': 'Giải đấu',
      'table_slow': 'Chậm',
      'table_medium': 'Trung bình',
      'table_fast': 'Nhanh',
      'mood_great': 'Tuyệt vời',
      'mood_good': 'Tốt',
      'mood_okay': 'Bình thường',
      'mood_tired': 'Mệt',
      'mood_bad': 'Kém',
      'condition_excellent': 'Xuất sắc',
      'condition_good': 'Tốt',
      'condition_okay': 'Bình thường',
      'condition_tight': 'Căng',
      'condition_painful': 'Đau',
      'readiness_excellent': 'Xuất sắc',
      'readiness_good': 'Tốt',
      'readiness_moderate': 'Trung bình',
      'readiness_low': 'Thấp',
      'readiness_poor': 'Kém',
      'quick_actions': 'Thao tác nhanh',
      'start_practice': 'Bắt đầu tập',
      'start_match': 'Bắt đầu đấu',
      'continue_session': 'Tiếp tục',
      'current_equipment': 'Dụng cụ hiện tại',
      'break_cue': 'Cơ phá',
      'cue_type_playing': 'Cơ chơi',
      'cue_type_break': 'Cơ phá',
      'cue_type_jump': 'Cơ nhảy',
      'cue_type_break_jump': 'Cơ phá + nhảy',
      'add_equipment': 'Thêm cơ đầu tiên',
      'coach_insight': 'Gợi ý Huấn luyện viên',
      'weekly_trend': 'Tuần này',
      'monthly_trend': 'Tháng này',
      'recent_sessions': 'Các buổi gần đây',
      'see_all': 'Xem tất cả',
      'no_sessions_yet': 'Chưa có buổi nào',
      'log_readiness': 'Điền tình trạng hôm nay',
      'tap_to_log': 'Bấm để ghi nhận',
      'performance_score': 'Điểm Hiệu Suất',
      'break_and_run': 'Phá & Chạy',
      'session_finished': 'Buổi đã kết thúc!',
      'view_summary': 'Xem Tóm tắt',
      'select_match_type': 'Chọn Loại Trận',
      'select_session_type': 'Chọn Loại Buổi',
      'match_details': 'Chi Tiết Trận',
      'finish_match': 'Kết Thúc Trận',
      'edit_match': 'Sửa Trận',
      'delete_match': 'Xóa Trận',
      'no_racks': 'Chưa có ván nào',
      'opponent': 'Đối thủ',
      'race_to': 'Đấu đến',
      'race_to_custom': 'Đấu đến số ván tùy chọn…',
      // Task 02: Shot recording wizard
      'shot_intent': 'Bạn định làm gì?',
      'shot_type_label': 'Loại cú đánh',
      'miss_reason_label': 'Sai ở đâu?',
      'shot_saved': 'Đã lưu cú đánh',
      'intent_pot': 'Đưa bi',
      'intent_position': 'Chấm bi',
      'intent_safety': 'An toàn',
      'intent_break': 'Phá',
      'intent_escape': 'Thoát',
      'miss_reason_aim': 'Ngắm',
      'miss_reason_speed': 'Lực',
      'miss_reason_position': 'Chấm bi',
      'miss_reason_english': 'Xoáy',
      'miss_reason_kick': 'Đánh né',
      'miss_reason_rush': 'Vội',
      'miss_reason_nerves': 'Tâm lý',
      'miss_reason_bad_decision': 'Quyết định sai',
      // Player State System
      'pre_match_title': 'Sẵn sàng thi đấu?',
      'pre_match_subtitle': 'Kiểm tra nhanh trước khi bắt đầu — khác với sẵn sàng hàng ngày.',
      'pre_match_ready': 'Sẵn sàng thi đấu',
      'pre_match_warmed_up': 'Đã khởi động',
      'pre_match_hand_feel': 'Cảm giác cơ / vào tay',
      'skip': 'Bỏ qua',
      'player_state_title': 'Trạng thái người chơi',
      'player_state_warmup': 'Vào tay',
      'player_state_endurance': 'Sức bền',
      'player_state_not_enough_data': 'Chưa đủ dữ liệu — hãy chơi thêm vài rack.',
      'player_state_slow_starter': 'Bạn thường cần khoảng {racks} rack để vào tay. Nên khởi động trước các trận đấu.',
      'player_state_fast_starter': 'Bạn vào form nhanh — không cần khởi động dài.',
      'player_state_declines': 'Phong độ của bạn thường giảm quanh rack {rack}. Cân nhắc nghỉ ngắn sau mốc đó.',
      'player_state_steady': 'Bạn giữ phong độ ổn định suốt buổi chơi.',
      'endurance_title': 'Sức bền',
      'endurance_not_enough_data': 'Chưa đủ dữ liệu để đánh giá.',
      'endurance_score': 'Điểm sức bền',
      'endurance_steady': 'Bạn giữ phong độ ổn định trong suốt buổi chơi.',
      'endurance_declines': 'Phong độ của bạn thường giảm từ khoảng rack {rack}.',
      'endurance_cause_technical': 'Sự sa sút thiên về kỹ thuật — ngắm và vị trí, không phải thể lực.',
      'endurance_cause_physical': 'Sự sa sút thiên về thể lực — kiểm soát và lực giảm khi mệt.',
      'endurance_cause_mixed': 'Sự sa sút do cả hai — kỹ thuật lẫn thể lực.',
      'endurance_cause_unknown': 'Chưa đủ chi tiết để xác định nguyên nhân.',
      'endurance_recommended_race': 'Race {race} phù hợp với thể lực hiện tại của bạn.',
      'endurance_curve_title': 'Đường cong phong độ',
      'endurance_curve_subtitle': 'Chất lượng từng rack trong trận gần nhất.',
      'endurance_based_on': 'Dựa trên {matches} trận, {racks} rack.',
      'endurance_error': 'Không tải được dữ liệu sức bền.',
      'post_match_title': 'Bạn mệt mức nào?',
      'post_match_subtitle': 'Ghi nhanh mức mệt sau trận này.',
      'fatigue_none': 'Không mệt',
      'fatigue_light': 'Hơi mệt',
      'fatigue_tired': 'Mệt',
      'fatigue_exhausted': 'Rất mệt',
      'race_to_5': 'Đấu đến 5',
      'race_to_7': 'Đấu đến 7',
      'select_winner': 'Chọn Người Thắng',
      'match_winner': 'Người Thắng Trận',
      'you': 'Bạn',
      'winner': 'Người thắng',
      'select_as_active': 'Chọn làm Hoạt động',
      'add_cue': 'Thêm Cơ',
      'edit_cue': 'Sửa Cơ',
      'cue_name': 'Tên Cơ',
      'details': 'Chi tiết',
      'cue_added': 'Đã thêm cơ thành công',
      'cue_updated': 'Đã cập nhật cơ thành công',
      'cue_deleted': 'Đã xóa cơ',
      'delete_cue_confirm': 'Xóa cơ',
      'coach': 'Huấn luyện viên',
      'overview': 'Tổng quan',
      'insights': 'Phân tích',
      'ask': 'Hỏi',
      'ask_coach_hint': 'Hỏi huấn luyện viên...',
      'no_insights': 'Chưa có phân tích',
      'play_sessions_for_insights':
          'Chơi thêm buổi để nhận phân tích cá nhân hóa',
      'training_advice': 'Lời Khuyên Tập Luyện',
      'strengths': 'Điểm Mạnh',
      'weaknesses': 'Điểm Cần Cải Thiện',
      'coach_summary': 'Tóm Tắt Huấn Luyện Viên',
      'recommended_drill': 'Bài Tập Đề Xuất',
      'definition': 'Định nghĩa',
      'calculation': 'Cách tính',
      'target': 'Mục tiêu',
      'advice': 'Lời khuyên',
      'trend': 'Xu hướng',
      'current_value': 'Giá trị hiện tại',
      'total_wins': 'Tổng Thắng',
      'total_losses': 'Tổng Thua',
      'win_rate': 'Tỷ lệ Thắng',
      'shot_accuracy': 'Độ chính xác',
      'career_accuracy': 'Độ Chính Xác Sự Nghiệp',
      'recent_performance': 'Hiệu Suất Gần Đây',
      'improvement_tips': 'Mẹo Cải Thiện',
      'weekly_performance': 'Hiệu Suất Tuần',
      'accuracy_trend': 'Xu Hướng Độ Chính Xác',
      'close': 'Đóng',
      'total_events': 'Tổng Sự Kiện',
      'no_players_yet': 'Chưa có người chơi',
      'create_first_player': 'Tạo người chơi đầu tiên để bắt đầu',
      'add_player': 'Thêm Người Chơi',
      'delete_player': 'Xóa Người Chơi',
      'are_you_sure_delete': 'Bạn có chắc muốn xóa',
      'skill_level': 'Cấp độ Kỹ năng',
      'default_equipment': 'Dụng cụ Mặc định',
      'cue_name_hint': 'ví dụ: Predator REVO',
      'select_avatar_color': 'Chọn Màu Đại diện',
      'beginner': 'Người mới',
      'intermediate': 'Trung bình',
      'advanced': 'Nâng cao',
      'expert': 'Chuyên gia',
      'professional': 'Chuyên nghiệp',
      'name_required': 'Tên là bắt buộc',
      'ghost_skill_level': 'Cấp độ Ghost',
      'ghost_challenge_won': 'Bạn Thắng!',
      'ghost_challenge_lost': 'Ghost Thắng!',
      'ghost_challenge_tie': 'Hòa!',
      'reset_challenge': 'Chơi Lại',
      'new_challenge': 'Thử Thách Mới',
      'who_won_rack': 'Ai thắng ván này?',
      'drill_progress': 'Tiến độ tập',
      'drill_complete': 'Hoàn thành bài tập!',
      'drill_instructions': 'Hướng dẫn',
      'try_again': 'Thử Lại',
      'filter_drills': 'Lọc bài tập',
      'category': 'Danh mục',
      'difficulty': 'Độ khó',
      'duration': 'Thời gian',
      'focus_areas': 'Trọng tâm',
      'clear_filters': 'Xóa lọc',
      'no_drills_found': 'Không tìm thấy bài tập',
      'adjust_filters': 'Thử điều chỉnh bộ lọc',
      'enroll_program': 'Đăng ký chương trình',
      'withdraw_program': 'Rút khỏi chương trình',
      'program_progress': 'Tiến độ chương trình',
      'current_week': 'Tuần {current}/{total}',
      'sessions_completed': '{completed}/{total} buổi',
      'upcoming_sessions': 'Các buổi tiếp theo',
      'program_overview': 'Tổng quan chương trình',
      'phases': 'Các giai đoạn',
      'total_sessions': 'Tổng buổi',
      'session_length': 'Thời lượng buổi tập',
      'week_progress': 'Tiến độ tuần {number}',
      'confirm_withdraw': 'Rút khỏi chương trình?',
      'withdraw_warning':
          'Tiến độ của bạn sẽ được lưu nhưng bạn cần bắt đầu lại.',
      'shot_type': 'Loại cú đánh',
      'shot_difficulty': 'Độ khó',
      'shot_result': 'Kết quả',
      'quick_add': 'Thêm nhanh',
      'shot_history': 'Lịch sử cú đánh',
      'clear_all_shots': 'Xóa tất cả',
      'undo_last_shot': 'Hoàn tác cú cuối',
      'made': 'Trúng',
      'missed': 'Trượt',
      'foul': 'Lỗi',
      'break': 'Phá bàn',
      'accuracy': 'Độ chính xác',
      'event_category': 'Danh mục',
      'event_type': 'Loại',
      'event_severity': 'Mức độ nghiêm trọng',
      'great_shot': 'Cú đánh hay',
      'mistake': 'Sai lầm',
      'safety_won': 'Thắng an toàn',
      'safety_lost': 'Thua an toàn',
      'dry_break': 'Phá khô',
      'mental_event': 'Tâm lý',
      'event_history': 'Lịch sử sự kiện',
      'minor': 'Nhẹ',
      'moderate': 'Trung bình',
      'significant': 'Đáng kể',
      'critical': 'Nghiêm trọng',
      'goals': 'Mục tiêu',
      'add_goal': 'Thêm mục tiêu',
      'today_goals': 'Mục tiêu hôm nay',
      'all_goals': 'Tất cả mục tiêu',
      'goal_progress': 'Tiến độ mục tiêu',
      'goals_completed': 'Mục tiêu đã hoàn thành',
      'set_goals': 'Đặt mục tiêu',
      'priority': 'Ưu tiên',
      'low': 'Thấp',
      'high': 'Cao',
      'urgent': 'Khẩn cấp',
      'completed': 'Hoàn thành',
      'abandoned': 'Đã từ bỏ',
      'overdue': 'Quá hạn',
      'days_remaining': 'Còn {days} ngày',
      'abandon_goal': 'Từ bỏ mục tiêu',
      'delete_goal': 'Xóa mục tiêu',
      'current_vs_previous': 'Hiện tại vs Trước đó',
      'skill_comparison': 'So sánh kỹ năng',
      'improvement': 'Cải thiện',
      'undo_rack': 'Hoàn tác ván cuối',
      'undo_rack_confirm': 'Hoàn tác ván cuối?',
      'undo_rack_message':
          'Điều này sẽ xóa ván #{number} và cập nhật thống kê trận đấu.',
      'rack_undone': 'Đã hoàn tác ván #{number}',
      // Dashboard
      'quick_stats': 'Thống kê nhanh',
      'today_focus': 'Trọng tâm hôm nay',
      'current_streak': 'Ngày liên tiếp',
      'weekly_hours': 'Tuần này',
      'no_skills': 'Chưa có dữ liệu kỹ năng',
      'last_matches': '10 Trận gần nhất',
      'no_matches': 'Chưa có trận nào',
      'won': 'Thắng',
      'lost': 'Thua',
      'in_progress': 'Đang diễn ra',
      'unknown_cue': 'Cơ không xác định',
      'unknown_date': 'Ngày không xác định',
      'unknown_error': 'Lỗi không xác định',
      'retry': 'Thử lại',
      'error_loading_data': 'Lỗi tải dữ liệu',
      // Session
      'view_details': 'Xem chi tiết',
      // Equipment
      'my_cue': 'Cơ của tôi',
      'please_enter_cue_name': 'Vui lòng nhập tên cơ',
      'set_as_active_cue': '{name} đã đặt làm cơ chính',
      'set_as_break_cue': '{name} đã đặt làm cơ phá',
      'set_as_jump_cue': '{name} đã đặt làm cơ nhảy',
      // Match
      'race_to_progress': 'Tiến độ đấu đến {raceTo}',
      'match_info': 'Thông tin trận',
      'started': 'Bắt đầu',
      'ended': 'Kết thúc',
      'rack_timeline': 'Dòng thời gian ván',
      'racks': 'ván',
      'record_rack_result': 'Ghi nhận kết quả ván',
      'tap_to_record_rack': 'Bấm để ghi nhận kết quả ván tiếp theo',
      'no_racks_to_undo': 'Không có ván để hoàn tác',
      'undo_rack_action': 'Hoàn tác',
      'finished': 'Đã kết thúc',
      // Statistics
      'detailed_stats': 'Thống kê chi tiết',
      'event_analysis': 'Phân tích sự kiện',
      'by_category': 'Theo danh mục:',
      'play_more_sessions_skills': 'Chơi thêm buổi để xem phân tích kỹ năng',
      'data_points': 'điểm dữ liệu',
      'performance_metrics': 'Các chỉ số hiệu suất trong khoảng theo dõi',
      'aggregated_sessions': 'Tổng hợp từ tất cả các buổi và ván',
      'improve_weekly': 'Cải thiện 5% mỗi tuần',
      'adjust_practice': 'Xem lại điều gì hiệu quả và không. Điều chỉnh trọng tâm tập phù hợp.',
      'accuracy_over_time': 'Độ chính xác đánh cơ thay đổi theo thời gian',
      'rolling_average': 'Trung bình động của tỷ lệ thành công',
      'reach_70_accuracy': 'Đạt và duy trì độ chính xác 70%+',
      'focus_alignment': 'Tập trung vào căn chỉnh và đánh cơ. Ghi lại buổi tập để xem lại.',
      'focus_position_play': 'Tập trung vào điều bi để tạo thêm cơ hội ghi điểm',
      'practice_fundamentals': 'Luyện các cú đánh cơ bản và kỹ thuật căn chỉnh',
      'play_more_sessions': 'Chơi thêm buổi để xây dựng dữ liệu nhất quán',
      'keep_up_great_work': 'Tiếp tục phát huy! Hiệu suất của bạn rất tốt.',
      'stat_not_enough_data': 'Chưa có đủ dữ liệu.',
      'stat_play_more_unlock': 'Chơi thêm trận để mở phân tích.',
      'stat_match_won': 'Trận Đã Thắng',
      'stat_avg_balls_potted': 'Trung Bình Bi Vào Lỗ',
      'stat_avg_largest_run': 'Trung Bình Chuỗi Dài Nhất',
      'stat_avg_break_success': 'Trung Bình Phá Thành Công',
      'stat_avg_confidence': 'Trung Bình Tự Tin',
      'stat_common_mistakes': 'Lỗi Thường Gặp',
      'stat_common_strengths': 'Điểm Mạnh Thường Gặp',
      'stat_coach_insight': 'Gợi Ý Huấn Luyện Viên',
      'stat_category': 'Danh Mục',
      'stat_metric': 'Chỉ Số',
      'stat_detail': 'Chi Tiết',
      'stat_recommendation': 'Đề Xuất',
      'stat_no_data': 'Không Có Dữ Liệu',
      'stat_insight_reason': 'Lý Do',
      'stat_insight_recommendation': 'Đề Xuất',
      'stat_insight_benefit': 'Lợi Ích Kỳ Vọng',
      'stat_trend_current': 'Hiện Tại',
      'stat_trend_previous': 'Trước Đó',
      'stat_trend_difference': 'Chênh Lệch',
      'stat_reason': 'Lý Do',
      'stat_expected_improvement': 'Cải Thiện Kỳ Vọng',
      'stat_common_miss_type': 'Loại Miss Thường Gặp',
      'stat_most_frequent_error': 'Lỗi Thường Xuất Hiện',
      'stat_accuracy_trend': 'Xu Hướng Độ Chính Xác',
      'stat_main_reason': 'Lý Do Chính',
      'stat_improvement_suggestion': 'Gợi Ý Cải Thiện',
      'stat_drill_down_title': 'Phân Tích Chi Tiết',
      'stat_summary': 'Tóm Tắt',
      'stat_drill_down_empty': 'Chưa có đủ dữ liệu. Chơi thêm trận để mở phân tích.',
      'stat_recommendation_source': 'Vì {reason}, đề xuất {drill}.',
      // Coach
      'analysis': 'Phân tích',
      'coach_score': 'Điểm Coach',
      'skill_score': 'Điểm Kỹ năng',
      'trend_score': 'Điểm Xu hướng',
      // Daily Readiness
      'ready_score': 'Sẵn sàng',
      'recovery_score': 'Phục hồi',
      'wrist_condition': 'Cổ tay',
      'back_condition': 'Lưng',
      // Session Summary
      'suggested': 'Đề xuất',
      // Rack
      'rack_summary': 'Tóm tắt Ván',
      'biggest_mistake': 'Sai lầm lớn nhất',
      'biggest_strength': 'Điểm mạnh lớn nhất',
      'rack_confidence': 'Mức tự tin',
      'confidence_very_low': 'Rất thấp',
      'confidence_low': 'Thấp',
      'confidence_medium': 'Trung bình',
      'confidence_high': 'Cao',
      'confidence_very_high': 'Rất cao',
      // Settings
      'system_default': 'Mặc định hệ thống',
      'measurement_cm': 'Centimet (cm)',
      'measurement_inch': 'Inch (in)',
      // Match Selection
      'select_match': 'Chọn Trận',
      'continue_match': 'Tiếp tục Trận',
      'no_sessions_to_continue': 'Không có buổi nào để tiếp tục',
      // Coach Presentation
      'coach_no_recommendations': 'Chưa có khuyến nghị. Hoàn thành thêm buổi chơi để nhận phân tích.',
      'coach_todays_focus': 'Trọng tâm hôm nay',
      'coach_primary_focus': 'Trọng tâm chính',
      'coach_secondary_focus': 'Trọng tâm phụ',
      'coach_observation': 'Vấn đề',
      'coach_evidence': 'Lý do',
      'coach_expected_improvement': 'Cải thiện mong đợi',
      'coach_recommended_drill': 'Bài tập đề xuất',
      'coach_problem': 'Vấn đề',
      'coach_reason': 'Lý do',
      'coach_benefit': 'Lợi ích kỳ vọng',
      'coach_no_training_plan': 'Chưa có kế hoạch tập luyện',
      'coach_complete_sessions_for_plan': 'Hoàn thành thêm buổi chơi để nhận kế hoạch tập luyện cá nhân',
      'coach_todays_plan': 'Kế hoạch hôm nay',
      'coach_start_training': 'Bắt đầu tập',
      'coach_drill_info': 'Thông tin bài tập',
      'coach_difficulty': 'Độ khó',
      'coach_duration': 'Thời gian',
      'coach_short_description': 'Mô tả ngắn',
      'coach_start_drill': 'Bắt đầu bài tập',
      'coach_unavailable': 'Không khả dụng',
      'coach_history_today': 'Hôm nay',
      'coach_history_yesterday': 'Hôm qua',
      'coach_history_last_7_days': '7 ngày gần nhất',
      'coach_history_last_30_days': '30 ngày gần nhất',
      'coach_history_completed': 'Hoàn thành',
      'coach_history_result': 'Kết quả',
      'coach_performance': 'Hiệu suất',
      'coach_consistency': 'Ổn định',
      'coach_confidence': 'Tự tin',
      'coach_training_distribution': 'Phân bố tập luyện',
      'coach_improvement': 'Cải thiện',
      'coach_regression': 'Suy giảm',
      'coach_equipment_analysis': 'Phân tích dụng cụ',
      'coach_match_analysis': 'Phân tích trận đấu',
      'coach_recommendation_history': 'Lịch sử khuyến nghị',
      'coach_not_enough_data': 'Chưa có đủ dữ liệu. Chơi thêm trận để mở phân tích AI.',
      'warmup': 'Khởi động',
      'cooldown': 'Hồi phục',
      'minutes_short': 'phút',
      'drills_short': 'bài tập',
      'target_score': 'điểm mục tiêu',
      'intensity_heavy': 'Tập nặng',
      'intensity_normal': 'Bình thường',
      'intensity_light': 'Tập nhẹ',
      'intensity_recovery': 'Phục hồi',
      'category_health': 'Sức khỏe',
      'category_readiness': 'Sẵn sàng',
      'category_mental': 'Tâm lý',
      'category_skill_weakness': 'Điểm yếu',
      'category_training_plan': 'Kế hoạch',
      'category_equipment': 'Dụng cụ',
      'category_recovery': 'Phục hồi',
      'category_general': 'Chung',
      // Localization
      'localization': 'Ngôn ngữ & Địa phương',
      'appearance': 'Giao diện',
      // Task 12 — Data Center
      'dc_title': 'Trung tâm dữ liệu',
      'dc_section_backup': 'Sao lưu & Phục hồi',
      'dc_section_export': 'Xuất dữ liệu',
      'dc_section_info': 'Thông tin CSDL',
      'dc_section_maintenance': 'Bảo trì',
      'dc_backup_desc': 'Lưu bản sao lưu toàn bộ dữ liệu ra file.',
      'dc_create_backup': 'Tạo bản sao lưu',
      'dc_backup_created': 'Đã tạo bản sao lưu',
      'dc_no_backups': 'Chưa có bản sao lưu.',
      'dc_rows': 'dòng',
      'dc_restore': 'Phục hồi',
      'dc_restore_confirm_title': 'Phục hồi bản sao lưu này?',
      'dc_restore_confirm_body':
          'Thao tác này thay thế TOÀN BỘ dữ liệu hiện tại bằng bản sao lưu ({rows} dòng). Không thể hoàn tác.',
      'dc_restore_ok': 'Đã phục hồi {rows} dòng.',
      'dc_export_desc': 'Xuất một module dạng JSON hoặc CSV.',
      'dc_export_ok': 'Đã lưu file xuất',
      'dc_export_matches': 'Lịch sử trận đấu',
      'dc_export_training': 'Luyện tập',
      'dc_export_goals': 'Mục tiêu',
      'dc_export_equipment': 'Thiết bị',
      'dc_export_shots': 'Cú đánh',
      'dc_db_version': 'Phiên bản schema',
      'dc_backup_format': 'Định dạng sao lưu',
      'dc_db_size': 'Kích thước CSDL',
      'dc_verify': 'Kiểm tra toàn vẹn',
      'dc_verify_desc': 'Kiểm tra CSDL có bị lỗi không.',
      'dc_verify_ok': 'Kiểm tra toàn vẹn đạt.',
      'dc_verify_fail': 'Phát hiện vấn đề khi kiểm tra.',
      'dc_compact': 'Nén CSDL',
      'dc_compact_desc': 'Thu hồi dung lượng trống (VACUUM).',
      'dc_compact_ok': 'Đã nén CSDL.',
      'dc_clear_temp': 'Dọn file tạm',
      'dc_clear_temp_desc': 'Xóa các file xuất đã tạo.',
      'dc_clear_temp_ok': 'Đã xóa {n} file.',
      'dc_err_format': 'Định dạng sao lưu mới hơn phiên bản app này.',
      'dc_err_schema': 'Bản sao lưu từ phiên bản CSDL khác.',
      'dc_err_restore': 'Phục hồi thất bại. Dữ liệu không bị thay đổi.',
      'dc_err_parse': 'Không đọc được file sao lưu.',
      // Task 13 — Tournament & League
      'tnmt_title': 'Giải đấu',
      'tnmt_new': 'Giải đấu mới',
      'tnmt_create': 'Tạo giải đấu',
      'tnmt_name': 'Tên giải đấu',
      'tnmt_name_required': 'Vui lòng nhập tên.',
      'tnmt_type': 'Thể thức',
      'tnmt_location': 'Địa điểm',
      'tnmt_start_date': 'Ngày bắt đầu',
      'tnmt_end_date': 'Ngày kết thúc',
      'tnmt_notes': 'Ghi chú',
      'tnmt_load_error': 'Không tải được giải đấu.',
      'tnmt_not_found': 'Không tìm thấy giải đấu.',
      'tnmt_empty_title': 'Chưa có giải đấu',
      'tnmt_empty_body': 'Tạo giải đấu để sắp xếp các trận thành nhánh đấu, giải vòng tròn hoặc league.',
      'tnmt_delete_title': 'Xóa giải đấu này?',
      'tnmt_delete_body': 'Nhánh đấu và người tham gia sẽ bị xóa. Các trận đã ghi được giữ nguyên.',
      'tnmt_type_singleElimination': 'Loại trực tiếp',
      'tnmt_type_singleElimination_desc': 'Thua một trận là bị loại.',
      'tnmt_type_doubleElimination': 'Loại kép',
      'tnmt_type_doubleElimination_desc': 'Thua một trận rớt xuống nhánh thua.',
      'tnmt_type_roundRobin': 'Vòng tròn',
      'tnmt_type_roundRobin_desc': 'Mọi người đấu với nhau một lần.',
      'tnmt_type_league': 'League',
      'tnmt_type_league_desc': 'Vòng tròn tính điểm xếp hạng.',
      'tnmt_status_upcoming': 'Sắp diễn ra',
      'tnmt_status_active': 'Đang diễn ra',
      'tnmt_status_completed': 'Đã kết thúc',
      'tnmt_tab_participants': 'Người tham gia',
      'tnmt_tab_bracket': 'Nhánh đấu',
      'tnmt_tab_standings': 'Bảng xếp hạng',
      'tnmt_tab_stats': 'Thống kê',
      'tnmt_add_participant': 'Thêm người',
      'tnmt_no_participants': 'Chưa có người tham gia.',
      'tnmt_pick_player': 'Chọn người chơi',
      'tnmt_add_guest': 'Thêm khách',
      'tnmt_guest_name': 'Tên khách',
      'tnmt_guest': 'Khách',
      'tnmt_player': 'Người chơi',
      'tnmt_set_seed': 'Đặt hạt giống',
      'tnmt_seed_hint': 'Số hạt giống (1 = cao nhất). Để trống để xóa.',
      'tnmt_generate_bracket': 'Tạo nhánh đấu',
      'tnmt_bracket_created': 'Đã tạo nhánh đấu.',
      'tnmt_bracket_locked': 'Nhánh đấu đã có kết quả — xóa kết quả trước khi tạo lại.',
      'tnmt_no_bracket': 'Chưa có nhánh đấu. Thêm ít nhất 2 người rồi tạo nhánh đấu.',
      'tnmt_tbd': 'Chưa xác định',
      'tnmt_tap_to_record': 'Chạm để ghi kết quả',
      'tnmt_record_result': 'Ghi kết quả',
      'tnmt_racks': 'ván',
      'tnmt_round': 'Vòng',
      'tnmt_round_final': 'Chung kết',
      'tnmt_round_semi': 'Bán kết',
      'tnmt_round_quarter': 'Tứ kết',
      'tnmt_no_standings': 'Chưa có kết quả. Bảng xếp hạng hiện sau trận đầu tiên.',
      'tnmt_col_rank': '#',
      'tnmt_col_player': 'Người chơi',
      'tnmt_col_w': 'T',
      'tnmt_col_l': 'B',
      'tnmt_col_rackdiff': 'Hiệu ván',
      'tnmt_col_pts': 'Điểm',
      'tnmt_stat_participants': 'Người tham gia',
      'tnmt_stat_fixtures': 'Tổng số trận',
      'tnmt_stat_played': 'Đã đấu',
      'tnmt_stat_remaining': 'Sẵn sàng đấu',
      'tnmt_stat_racks': 'Số ván đã ghi',
      'tnmt_stat_empty': 'Thống kê hiện khi có trận được ghi.',
      'tnmt_champion': 'Vô địch',
      // Task 14 — Club & Community
      'club_title': 'Câu lạc bộ',
      'club_new': 'CLB mới',
      'club_create': 'Tạo CLB',
      'club_name': 'Tên CLB',
      'club_name_required': 'Vui lòng nhập tên.',
      'club_location': 'Địa điểm',
      'club_description': 'Mô tả',
      'club_manager': 'Người quản lý',
      'club_load_error': 'Không tải được CLB.',
      'club_not_found': 'Không tìm thấy CLB.',
      'club_empty_title': 'Chưa có CLB',
      'club_empty_body': 'Tạo CLB để nhóm người chơi, theo dõi bảng xếp hạng nội bộ và tổ chức sự kiện.',
      'club_delete_title': 'Xóa CLB này?',
      'club_delete_body': 'CLB và thành viên sẽ bị xóa. Các trận, buổi tập và giải đấu đã liên kết được giữ nguyên.',
      'club_role_owner': 'Chủ CLB',
      'club_role_admin': 'Quản trị',
      'club_role_member': 'Thành viên',
      'club_guest': 'Khách',
      'club_invited': 'Đã mời',
      'club_tab_members': 'Thành viên',
      'club_tab_ranking': 'Xếp hạng',
      'club_tab_leaderboard': 'Bảng vàng',
      'club_tab_stats': 'Thống kê',
      'club_tab_history': 'Lịch sử',
      'club_no_members': 'Chưa có thành viên.',
      'club_add_member': 'Thêm thành viên',
      'club_pick_player': 'Chọn người chơi',
      'club_add_guest': 'Thêm khách',
      'club_as_invite': 'Thêm dạng lời mời (chưa xác nhận)',
      'club_guest_name': 'Tên khách',
      'club_confirm_invite': 'Xác nhận lời mời',
      'club_no_ranking': 'Chưa có xếp hạng. Liên kết trận của CLB để tạo xếp hạng.',
      'club_col_rank': '#',
      'club_col_member': 'Thành viên',
      'club_col_played': 'Trận',
      'club_col_w': 'Thắng',
      'club_col_winrate': 'Tỷ lệ',
      'club_col_streak': 'Chuỗi',
      'club_col_pts': 'Điểm',
      'club_pts_short': 'điểm',
      'club_period_week': 'Tuần',
      'club_period_month': 'Tháng',
      'club_period_year': 'Năm',
      'club_no_leaderboard': 'Không có trận trong kỳ này.',
      'club_stat_matches': 'Tổng số trận',
      'club_stat_racks': 'Tổng số ván',
      'club_stat_training': 'Tổng giờ luyện tập',
      'club_stat_most_active': 'Luyện nhiều nhất',
      'club_stat_most_wins': 'Thắng nhiều nhất',
      'club_stat_most_improved': 'Tiến bộ nhiều nhất',
      'club_stat_empty': 'Thống kê hiện khi có trận CLB được liên kết.',
      'club_hist_matches': 'Trận của CLB',
      'club_hist_trainings': 'Buổi tập của CLB',
      'club_hist_tournaments': 'Giải đấu của CLB',
      'club_hist_empty': 'Chưa liên kết gì.',
      'club_unlink': 'Bỏ liên kết',
      // Task 11 — Player Timeline & Career
      'career_title': 'Hành trình & Sự nghiệp',
      'career_summary_title': 'Tổng quan sự nghiệp',
      'career_since': 'Thời gian đồng hành',
      'career_days': 'ngày',
      'career_matches_won': 'Trận thắng',
      'career_goals_done': 'Goal hoàn thành',
      'career_equipment_used': 'Thiết bị đã dùng',
      'career_empty': 'Chưa có lịch sử. Chơi một buổi để bắt đầu hành trình.',
      'career_no_filtered': 'Không có sự kiện khớp bộ lọc.',
      'career_filter_all': 'Tất cả',
      'career_filter_session': 'Buổi chơi',
      'career_filter_match': 'Trận đấu',
      'career_filter_goal': 'Mục tiêu',
      'career_filter_achievement': 'Thành tích',
      'career_filter_equipment': 'Thiết bị',
      'career_filter_training': 'Luyện tập',
      'career_match_win': 'Thắng trận',
      'career_match_loss': 'Thua trận',
      'career_race': 'Race to',
      'career_equipment_added': 'Thiết bị mới',
      'career_training_session': 'Buổi luyện tập',
      'career_goal_completed': 'Hoàn thành Goal',
      'career_achievement_unlocked': 'Mở khóa thành tích',
      'career_session_practice': 'Buổi luyện tập',
      'career_session_match': 'Buổi thi đấu',
      'career_session_started': 'Bắt đầu buổi chơi',
      // Task 09 — Training Center
      // Task 10 — Goal & Progress Center
      'gc_title': 'Trung tâm mục tiêu',
      'gc_section_goals': 'Mục tiêu',
      'gc_section_achievements': 'Thành tích',
      'gc_section_streaks': 'Chuỗi',
      'gc_section_milestones': 'Cột mốc',
      'gc_new_goal': 'Mục tiêu mới',
      'gc_goal_title': 'Tên mục tiêu',
      'gc_metric': 'Theo dõi gì',
      'gc_target_amount': 'Số lượng mục tiêu',
      'gc_target_amount_help': 'Cần thêm bao nhiêu kể từ bây giờ',
      'gc_target_percent': 'Tỷ lệ mục tiêu',
      'gc_target_percent_help': 'Tỷ lệ thành công cần đạt',
      'gc_note_optional': 'Ghi chú (không bắt buộc)',
      'gc_title_required': 'Vui lòng nhập tên mục tiêu',
      'gc_amount_invalid': 'Nhập mục tiêu hợp lệ',
      'gc_no_goals': 'Chưa có mục tiêu. Nhấn + để tạo.',
      'gc_goal_done': 'Hoàn thành',
      'gc_default_badge': 'Mặc định',
      'gc_new': 'MỚI',
      'gc_delete_goal': 'Xóa mục tiêu',
      'gc_delete_goal_confirm': 'Chỉ xóa mục tiêu này. Dữ liệu đã ghi không bị ảnh hưởng.',
      'gc_notice_progress': '{goal}: chỉ còn {percent}% là hoàn thành.',
      'gc_notice_done': 'Bạn đã hoàn thành: {goal}!',
      // Goal metrics
      'gc_metric_matches_won': 'Trận thắng',
      'gc_metric_break_and_runs': 'Break & Run',
      'gc_metric_long_pot_rate': 'Tỷ lệ Long Pot',
      'gc_metric_stop_shot_rate': 'Tỷ lệ Stop Shot',
      'gc_metric_total_shots': 'Tổng số Shot',
      'gc_metric_total_matches': 'Tổng số Match',
      'gc_metric_total_racks': 'Tổng số Rack',
      'gc_metric_practice_hours': 'Giờ luyện tập',
      'gc_metric_scratch_free_matches': 'Trận không Scratch',
      'gc_metric_training_day_streak': 'Chuỗi ngày luyện tập',
      // Default goals
      'gc_default_first_bnr': 'Break & Run đầu tiên',
      'gc_default_long_pot_70': 'Long Pot trên 70%',
      'gc_default_stop_shot_80': 'Stop Shot trên 80%',
      'gc_default_win_10': 'Thắng 10 trận',
      'gc_default_scratch_free_10': 'Không Scratch trong 10 trận',
      // Achievements
      'gc_ach_first_match_win': 'Trận thắng đầu tiên',
      'gc_ach_first_match_win_desc': 'Thắng trận đầu tiên',
      'gc_ach_first_bnr': 'Break & Run đầu tiên',
      'gc_ach_first_bnr_desc': 'Break và dọn sạch một Rack',
      'gc_ach_win_streak_5': 'Chuỗi thắng 5',
      'gc_ach_win_streak_5_desc': 'Thắng 5 trận liên tiếp',
      'gc_ach_shots_1000': '1.000 Shot',
      'gc_ach_shots_1000_desc': 'Ghi 1.000 Shot',
      'gc_ach_matches_100': '100 Match',
      'gc_ach_matches_100_desc': 'Chơi 100 trận',
      'gc_ach_long_pot_70': 'Long Pot 70%',
      'gc_ach_long_pot_70_desc': 'Đạt tỷ lệ Long Pot 70%',
      // Streaks
      'gc_streak_train_7': 'Luyện tập 7 ngày',
      'gc_streak_train_7_desc': '7 ngày luyện tập liên tiếp',
      'gc_streak_train_10': 'Luyện tập 10 ngày',
      'gc_streak_train_10_desc': '10 ngày luyện tập liên tiếp',
      'gc_streak_scratch_free_10': 'Không Scratch 10',
      'gc_streak_scratch_free_10_desc': '10 trận không Scratch',
      // Milestones
      'gc_mile_matches_100': '100 Match',
      'gc_mile_matches_100_desc': 'Đạt 100 trận đã chơi',
      'gc_mile_racks_500': '500 Rack',
      'gc_mile_racks_500_desc': 'Đạt 500 Rack đã chơi',
      'gc_mile_shots_10000': '10.000 Shot',
      'gc_mile_shots_10000_desc': 'Đạt 10.000 Shot đã ghi',
      'gc_mile_hours_100': '100 giờ',
      'gc_mile_hours_100_desc': 'Đạt 100 giờ luyện tập',
      'training_center_title': 'Trung tâm luyện tập',
      'tc_start_session': 'Bắt đầu buổi luyện',
      'tc_progress': 'Tiến độ',
      'tc_custom_drill': 'Bài tập riêng',
      'tc_categories': 'Nhóm bài tập',
      'tc_recent': 'Gần đây',
      'tc_load_error': 'Không tải được bài tập.',
      'tc_no_drills': 'Chưa có bài tập nào.',
      'tc_custom_drill_title': 'Bài tập riêng mới',
      'tc_drill_name': 'Tên bài tập',
      'tc_drill_name_hint': 'vd: Pot bi thẳng xa',
      'tc_name_required': 'Vui lòng nhập tên.',
      'tc_category': 'Nhóm',
      'tc_target_reps': 'Mục tiêu số lần',
      'tc_reps_invalid': 'Nhập số lớn hơn 0.',
      'tc_success_criteria': 'Điều kiện thành công (tùy chọn)',
      'tc_success_criteria_hint': 'Bạn tính thế nào là đạt?',
      'tc_save': 'Lưu',
      'tc_saved': 'Đã lưu.',
      'tc_progress_title': 'Tiến độ',
      'tc_progress_empty': 'Chưa có lịch sử luyện tập. Chạy một buổi để xem tiến độ.',
      'tc_prev': 'Kỳ trước',
      'tc_current': 'Hiện tại',
      'tc_progress_need_more': 'Chưa đủ dữ liệu để so sánh.',
      'tc_session_title': 'Buổi luyện tập',
      'tc_add_drill': 'Thêm bài tập',
      'tc_session_empty': 'Thêm một bài tập để bắt đầu ghi Đạt / Miss.',
      'tc_target': 'Mục tiêu',
      'tc_miss': 'Miss',
      'tc_hit': 'Đạt',
      'tc_undo': 'Hoàn tác',
      'tc_pick_drill': 'Chọn bài tập',
      'tc_search_hint': 'Tìm bài tập',
    },
  };

  String get(String key) {
    // RFC-302 Task 1: never crash on a missing key. Fall back through the
    // current locale -> English -> the key itself, so an unmapped or
    // malformed key degrades to visible text instead of throwing
    // "Null check operator used on a null value".
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'vi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
