/// Recommendation generated by Coach
class Recommendation {
  final String goalId;
  final String goalName;
  final String knowledgeId;
  final String knowledgeName;
  final String drillId;
  final String drillName;
  final String videoId;
  final String videoSegment;
  final int durationMinutes;
  final double confidence;
  final String reason;

  const Recommendation({
    required this.goalId,
    required this.goalName,
    required this.knowledgeId,
    required this.knowledgeName,
    required this.drillId,
    required this.drillName,
    required this.videoId,
    required this.videoSegment,
    required this.durationMinutes,
    required this.confidence,
    required this.reason,
  });

  Map<String, dynamic> toJson() => {
        'goalId': goalId,
        'goalName': goalName,
        'knowledgeId': knowledgeId,
        'knowledgeName': knowledgeName,
        'drillId': drillId,
        'drillName': drillName,
        'videoId': videoId,
        'videoSegment': videoSegment,
        'durationMinutes': durationMinutes,
        'confidence': confidence,
        'reason': reason,
      };

  factory Recommendation.fromJson(Map<String, dynamic> json) => Recommendation(
        goalId: json['goalId'] as String,
        goalName: json['goalName'] as String,
        knowledgeId: json['knowledgeId'] as String,
        knowledgeName: json['knowledgeName'] as String,
        drillId: json['drillId'] as String,
        drillName: json['drillName'] as String,
        videoId: json['videoId'] as String,
        videoSegment: json['videoSegment'] as String,
        durationMinutes: json['durationMinutes'] as int,
        confidence: (json['confidence'] as num).toDouble(),
        reason: json['reason'] as String,
      );
}
