import 'package:flutter_test/flutter_test.dart';
import 'package:pool_os/contracts/runtime_composition_contracts.dart';
import 'package:pool_os/contracts/runtime_execution_graph_contracts.dart';
import 'package:pool_os/contracts/runtime_pipeline_contracts.dart';

void main() {
  final pipeline = const RuntimePipelineEngine().build(composition: const RuntimeCompositionEngine().compose(nodes: [const RuntimeNodeContract(id: 'a', kind: RuntimeNodeKind.session, sourceContractVersion: 1, sourceDigest: 'a'), const RuntimeNodeContract(id: 'b', kind: RuntimeNodeKind.promptAssembly, sourceContractVersion: 1, sourceDigest: 'b'), const RuntimeNodeContract(id: 'c', kind: RuntimeNodeKind.activation, sourceContractVersion: 1, sourceDigest: 'c')], edges: const [RuntimeEdgeContract(fromId: 'a', toId: 'b'), RuntimeEdgeContract(fromId: 'b', toId: 'c')]), stages: const [PipelineStage(id: 'first', runtimeNodeId: 'a'), PipelineStage(id: 'second', runtimeNodeId: 'b'), PipelineStage(id: 'third', runtimeNodeId: 'c')], transitions: const [PipelineTransition(fromStageId: 'first', toStageId: 'second'), PipelineTransition(fromStageId: 'second', toStageId: 'third')]);
  const nodes = [ExecutionNode(id: 'one', stageId: 'first'), ExecutionNode(id: 'two', stageId: 'second'), ExecutionNode(id: 'three', stageId: 'third')];
  const dependencies = [ExecutionDependency(fromNodeId: 'one', toNodeId: 'two'), ExecutionDependency(fromNodeId: 'two', toNodeId: 'three')];
  test('graph is deterministic, immutable, reachable, and pipeline-bound', () { final first = const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes, dependencies: dependencies); final second = const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes.reversed.toList(), dependencies: dependencies.reversed.toList()); expect(second.digest, first.digest); expect(first.pipelineDigest, pipeline.digest); expect(() => first.nodes.add(nodes.first), throwsUnsupportedError); });
  test('duplicate node or dependency fails closed', () { expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: [...nodes, nodes.first], dependencies: dependencies), throwsArgumentError); expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes, dependencies: [...dependencies, dependencies.first]), throwsArgumentError); });
  test('orphan node fails closed', () => expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: [...nodes, const ExecutionNode(id: 'orphan', stageId: 'first')], dependencies: dependencies), throwsArgumentError));
  test('cyclic graph fails closed', () => expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes, dependencies: [...dependencies, const ExecutionDependency(fromNodeId: 'three', toNodeId: 'one')]), throwsArgumentError));
  test('stale dependency or stage binding fails closed', () { expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes, dependencies: [...dependencies, const ExecutionDependency(fromNodeId: 'missing', toNodeId: 'one')]), throwsArgumentError); expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: const [ExecutionNode(id: 'bad', stageId: 'missing')], dependencies: const []), throwsArgumentError); });
  test('missing pipeline stage fails closed', () => expect(() => const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes.sublist(0, 2), dependencies: dependencies), throwsArgumentError));
  test('builder does not mutate pipeline', () { final before = pipeline.toJson(); const RuntimeExecutionGraphBuilder().build(pipeline: pipeline, nodes: nodes, dependencies: dependencies); expect(pipeline.toJson(), before); });
}
